### ISSUE TITLE
help wanted: Web APIs' implementation

### ISSUE THREAD

**Issue by kyranet** [denoland/deno#1047]
Previously discussed in https://github.com/denoland/deno/issues/82, this is a meta issue to help contributors (and future ones) track some of the Web APIs in deno.

- [ ] [EventTarget][EventTargetMDN] - [spec][EventTargetWHATWG] - #2029 
- [x] [Event][EventMDN] - [spec][EventWHATWG] - @acconrad 
- [x] [CustomEvent][CustomEventMDN] - [spec][CustomEventWHATWG]
- [x] [WebSocket][WebSocketMDN] - [spec][WebSocketWHATWG] #1254 
- [x] [URL][URLMDN] - [spec][URLWHATWG]
- [x] [URLSearchParams][URLSearchParamsMDN] - [spec][URLSearchParamsWHATWG] - @kyranet 
- [x] [Worker][WorkerMDN] - [spec][WorkerWHATWG] #1222 

> **Note**: The HTTP web server first will be done before `WebSocket`'s initial development. However, `WebSocket` extends `EventTarget` which inherently requires Event. `Worker` also extends `EventTarget`.

Additionally, we could later implement the [Web Audio API](https://webaudio.github.io/web-audio-api/) for audio processing, and the [HTML Canvas 2D Context API](https://www.w3.org/TR/2dcontext/) for image processing/generation, too.

[EventTargetMDN]: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/EventTarget
[EventTargetWHATWG]: https://dom.spec.whatwg.org/#dom-eventtarget-eventtarget
[EventMDN]: https://developer.mozilla.org/en-US/docs/Web/API/Event
[EventWHATWG]: https://dom.spec.whatwg.org/#interface-event
[CustomEventMDN]: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent
[CustomEventWHATWG]: https://dom.spec.whatwg.org/#interface-customevent
[WebSocketMDN]: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket
[WebSocketWHATWG]: https://html.spec.whatwg.org/multipage/web-sockets.html#dom-websocket
[URLMDN]: https://developer.mozilla.org/en-US/docs/Web/API/URL
[URLWHATWG]: https://url.spec.whatwg.org/#api
[URLSearchParamsMDN]: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
[URLSearchParamsWHATWG]: https://url.spec.whatwg.org/#urlsearchparams
[WorkerMDN]: https://developer.mozilla.org/en-US/docs/Web/API/Worker
[WorkerWHATWG]: https://html.spec.whatwg.org/multipage/workers.html#worker

**Comment by kyranet** [comment]
I believe that the MDN docs and the WHATWG ones should suffice, they're also available in any modern browser so we can play around with those APIs.

There was a version of URL in the [golang version](https://github.com/denoland/deno/blob/golang/url.js) but it was removed in the rust rewrite. I'm currently working on URLSearchParams and later URL, but we can try to cooperate if you want 👍

**Comment by acconrad** [comment]
Perfect! I can take a look at Events then, although I will say this is pretty intimidating, that Golang spec is almost 700 lines

**Comment by ztplz** [comment]
I am working on `EventTarget`.

**Comment by kitsonk** [comment]
A good example of Web APIs implemented in plain JavaScript is [jsdom](https://github.com/jsdom/jsdom).

Most of the APIs we are talking about have interfaces in TypeScript which we should follow.  For example [`EventTarget`](https://github.com/denoland/deno_third_party/blob/33fa88485c6b32ebf8fc0c41d84ca2ece7f9a633/node_modules/typescript/lib/lib.dom.d.ts#L4940-L4961).

**Comment by acconrad** [comment]
@kyranet thanks for putting out #1049 that actually gives me a good guideline for following along for Event. I'll give that one a shot.

**Comment by acconrad** [comment]
@kyranet I couldn't comment on the merged PR but shouldn't the constructor for the URL search params be `?` since the spec mentions it as optional?

**Comment by KingDGrizzle** [comment]
I'm willing to give a shot at implementing the URL spec, if that's ok with everyone. I'll probably start by inspiring and / or porting the golang implementation.

**Comment by kyranet** [comment]
@acconrad 
> @kyranet I couldn't comment on the merged PR but shouldn't the constructor for the URL search params be `init?:` since the spec mentions it as optional?

It's actually optional, `= ""` implies it, tslint complained when I used both `init?:` and `= ""`, suggesting to use `init:` instead: https://github.com/denoland/deno/blob/c4bddc4651f583241193b80634a4f22abb02d582/js/url_search_params.ts#L5

From WHATWG: https://url.spec.whatwg.org/#interface-urlsearchparams

**Comment by ry** [comment]
Use node modules where possible - no need to reinvent the wheel. With URL there is already a node module.

**Comment by acconrad** [comment]
For everyone here if you're confused by the interface definitions within the WhatWG, check out [this doc](https://heycam.github.io/webidl/) on the official Interface Document Language :)

**Comment by ztplz** [comment]
@acconrad   Sorry for my delay PR. Github still is down, I will do it next day.

**Comment by acconrad** [comment]
@ztplz don't worry, I'm not in a rush, I still need to do a final draft of the `Event` API since I'm still learning how the spec operates myself :)

**Comment by acconrad** [comment]
I'll grab `Worker` next after `Event`/`EventInit` btw

**Comment by kyranet** [comment]
Just to clarify, add `EventInit` and assign both `Event` and `EventInit` to @acconrad, then assign `EventTarget` to @ztplz?

`Worker` is going to be pretty interesting to implement, I'm looking forward to seeing how it will be implemented in deno 😄

**Comment by mreinstein** [comment]
@ry deno's philosophy of following browser APIs has a lot going for it, and I've been keen to see this play out in the development. One question I have is how faithfully are we following this model?  a few points:

* having near-perfect browser API compaitibility would be awesome, avoiding node-isms are one of the big draws of this project (commonjs, etc)
* There are a handful of web APIs are  an unmitigated disaster (e.g., the audio APIs are just a complete mess.)
* I weep to think of our team spending time perfectly mimicking truly awful APIs. It seems like such a wasted opportunity to get something like audio right.

So I guess my question is does it make sense to replicate APIs that are really suffering from poor design? I understand the tradeoffs, I'd like to understand this project's philosophies.

**Comment by acconrad** [comment]
@mreinstein @ry would be good to know what level of compliance you are looking for as it relates to the Web IDL standard I referenced. For example, `readonly` in TypeScript does not mean the same thing as `readonly` in the Web IDL, which really means:

> This `prototype` property is `{ get: propGetter, configurable: true, enumerable: true }`

And to be truly compliant, you have to use `WeakMaps` for private state. Again, that's just one example but it's useful to know for both security reasons and quality standards.

**Comment by acconrad** [comment]
> Just to clarify, add `EventInit` and assign both `Event` and `EventInit` to @acconrad, then assign `EventTarget` to @ztplz?
> 
> `Worker` is going to be pretty interesting to implement, I'm looking forward to seeing how it will be implemented in deno 😄

Yeah that's just one example, I know someone else claimed `URL` too so it would just be good to see what is claimed and who claimed it so we can figure out what is left to tackle

**Comment by ztplz** [comment]
@ry  Do we need to add more type declarations for web APIs? `Element` is not defined  yet in `dom_type.ts`.

**Comment by ry** [comment]
@acconrad Regarding level of compliance - I don't have any particular opinions on this. Web scripts should run on Deno if they are using APIs we support - with little or no modification - that's all I care about. If you feel strongly about how this should be done, perhaps add some text to [the contributing guide](https://github.com/denoland/deno/blob/master/.github/CONTRIBUTING.md)? 

@ztplz Let's add them as necessary to support specific functionality that you need. I don't want to add a bunch of interfaces for APIs that are not usable. That goes for these above APIs here - I'm fine adding EventTarget - if it's needed for some specific functionality - but let's not add abstract utilities that are not used anywhere. There are many many web APIs - we are not trying to reimplement a complete headless chrome - so please add interfaces lazily.

**Comment by ry** [comment]
@kyranet  For URL, I used https://github.com/github/url-polyfill in the prototype: https://github.com/denoland/deno/blob/golang/url.js
If you can use it without forking and just putting it into package.json, that would be great. We should reduce the amount of code we have to maintain as much as possible. I forget why I forked it originally.

**Comment by kitsonk** [comment]
That URL implementation is clean and modern JavaScript.  My feeling is something like that could be included cleanly in Deno.  Some of the other polyfills aren't written as cleanly or have a lot of code to support older browsers, or rely on Node.js APIs, etc.

It is a fine balance between less maintaining of code and not dragging in a whole load of stuff and keeping type safety.

**Comment by acconrad** [comment]
I should also point out that there is already a free test suite out there for reaching Web API compliance:

https://github.com/web-platform-tests/wpt

We should try to leverage these with each of the interfaces we are implementing

**Comment by mrkurt** [comment]
We have a pretty clean URL implementation we can do a PR for if you wall want. The URL polyfills have been a headache for us over the last 8 mo:

https://github.com/superfly/fly.rs/blob/master/v8env/src/url.ts

**Comment by ry** [comment]
@mrkurt that would be appreciated - code looks good

**Comment by watilde** [comment]
To follow URL spec in WHATWG, here is a proper one:
https://github.com/jsdom/whatwg-url/

**Comment by ruphin** [comment]
Is the [Web Crypto API](https://www.w3.org/TR/WebCryptoAPI/) on the list of Web APIs we want to implement? There are excellent user space JS alternatives for most of endpoints in this API, but we need some cryptographically secure random source which cannot be done in user space.

**Comment by kyranet** [comment]
Most likely, yes @ruphin, cryptography is pretty important and I think we should support it.

**Comment by ruphin** [comment]
I need a secure random source for something I'm working on. I can take a stab at implementing `Crypto.getRandomValues` https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues

**Comment by acconrad** [comment]
@kyranet you can update this. @kitsonk added URL and I added in Event and EventTarget. I'm going to next work on improving the EventTarget implementation and then move onto CustomEvent after that.

**Comment by kevinkassimo** [comment]
@acconrad Ryan is working on workers alongside with native ES module (since now TS compiler goes to a worker).

**Comment by hayd** [comment]
@acconrad and websockets are in deno_std now https://github.com/denoland/deno_std/pull/84

**Comment by kevinkassimo** [comment]
@hayd I think we could possibly move client side `WebSocket` APIs from `deno_std` to the main repo as a global after a more careful review

**Comment by acconrad** [comment]
Just to update - everything here is done except for `EventTarget` which is an incomplete spec. I'm working on finalizing it today.

**Comment by acconrad** [comment]
Broken but an initial look at EventTarget: https://github.com/denoland/deno/pull/2028

**Comment by kyranet** [comment]
Updated! Let me know if I'm missing any other, I'm happy to update the list 😄

**Comment by kt3k** [comment]
This seems finished by #2377

**Comment by acconrad** [comment]
can confirm i added the last of the Web API implementations as @kt3k pointed out, this should be all set!

**Comment by kyranet** [comment]
Awesome! Done a last edit to link the last PR ❤️

**Comment by mash-graz** [comment]
> Additionally, we could later implement the Web Audio API for audio processing, ...

did anyone already try to enable WebAudio in deno as mentioned at the top of this historic issue?

utilizing [servo-media](https://github.com/servo/media), which is written in rust like deno itself, it should be perhaps possible to add this feature by experienced deno developers with acceptable efforts.
