### ISSUE TITLE
lsp: import quick fixes and import suggestions consider import maps

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#10951]
We don't properly consider import maps when providing import completion suggestions or quick fixes.

**Comment by kitsonk** [comment]
I've started working on this and it feels like it needs to be broken down into a few features, so this will be the master issue and the other features would be:

- [ ] Import completions include import map entries and provide completions similar to local workspace completions. (#13619)
- [ ] There is a diagnostic which determines if a specifier can be re-written to a specifier as an import map is issued, and there is a quick fix which re-writes the specifier. (#13620)
- [ ] When completing an import map specifier that resolves to a specifier covered by a registry completion, the completions are remapped to the import specifier. (#13621)
- [ ] When hovering over a specifier that resolves via an import map, there is information available about the import map resolution. (#13622)
- [ ] When choosing a quick fix for importing a workspace symbol, and an import map specifier can be applied, it is preferred. (#13623)
