### ISSUE TITLE
Q3 2021 roadmap

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#11168]
Here's a list of major features we would like to land in Q3

### CLI/Runtime/Core

- [ ] Introduce new subprocess API 
  - #11016
  - #5501
  - #11618
  - Maybe 1.15/1.16
- [ ] Overhaul testing API (https://github.com/denoland/deno/discussions/10771)
- [ ] Overhaul `deno doc` (https://github.com/denoland/deno_doc/issues/111, #8233)
  - Progress there, most user facing delivery in Q4
- [x] More options in configuration file (#3179)
  - import map config has not yet landed
  - how to integrate with deploy is unclear
  - maybe need playground project for exploring these ideas but worried about dojox situation
  - #11686
  - #11776
  - #11857
  - In progress, landing lint config in 1.14
  - Resolution of config file has made good progress
- [ ] Code Sign EXE for Windows and Mac https://github.com/denoland/deno/issues/575
  - https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#extended-validation-code-signing-certificates 
  - Bert to action
- [ ] Prompt by default (https://github.com/denoland/deno/issues/10183)
  - security concerns about stuffing prompt https://github.com/denoland/deno/issues/9750
  - call isatty and not prompt if not tty
  - Ry to champion in Q4
- [ ] Don't type check be default (https://github.com/denoland/deno/issues/11340)
  - kitson will attempt for 1.13
- [ ] Introduce cross-process `BroadcastChannel` (#10750)
  - Not for 1.14
- [x] Improve web crypto support: https://github.com/denoland/deno/issues/11690
  - Making forward progress (big missing functionality is import/export keys might make 1.14)
- [x] Stabilize native HTTP server API - `Deno.serveHttp` https://github.com/denoland/deno/pull/11544
- [x] Add ability to ignore SSL certificate errors (#1371)
- [x] #11338 
  - classic workers not making it for 1.13
  - need work upstream in WPT to support
  - all WPT tests are written to use classic workers
- [x] Remove native plugins API, introduce FFI API
  - #8490
  - #11152
- [x] Websocket support in native HTTP server API (https://github.com/denoland/deno/issues/10211, #10359)
- [x] Move docs to separate repo https://github.com/denoland/deno/issues/11391

### Language Server

- [ ] Registry Suggestions "v2" 
  - #10051
  -  #10093
  -  #10700
  - probably not for 1.14
- [ ] Better support for import maps
  - had a few bug fixes feature enhancements next
  - #10951
  - #10950 (maybe)
  - probably not 1.14
- [ ] Performance Improvements (#11032 and more)
  - partially done, more to do Q4
- [x] Refactoring fixes (denoland/vscode_deno#433)
- [x] Better documentation setting up development environment (focusing on Visual Studio Code, IntelliJ/WebStorm, and vim/NeoVim)
  - https://github.com/denoland/manual/pull/25
- [x] Support setting DENO_DIR in settings (denoland/vscode_deno#287)

### Standard Library

- [x] land collections API
- [x] http overhaul (https://github.com/denoland/deno_std/discussions/1034)

There are three minor release planned:
- 1.12.0 - July 13
- 1.13.0 - August 10
- 1.14.0 - September 14

This list is subject to change. Feedback and suggestions are welcome!

**Comment by bartlomieju** [comment]
All scheduled releases have already been shipped. Most of points that are still WIP were moved to https://github.com/denoland/deno/issues/12110.
