### ISSUE TITLE
Release "deno" crate.

### ISSUE THREAD

**Issue by ry** [denoland/deno#1209]
- [X] allocate name https://crates.io/crates/deno
- [X] make 'cargo check' work (i.e. basic cargo support) #1128 
- [x] gn and ninja should build into the same dir https://github.com/denoland/deno/pull/1184
- [] prebuilt V8 binaries to speed up build. orig #1217 - but reverted recently because sccache + s3 works so well
- [x] make 'cargo build' work #695 
  - [x] gn on windows uses `lld /llvmthinlto` linker which seems to be incompatible with `link.exe`. Partial attempt:  https://github.com/denoland/deno/pull/1231
  - [ ] <s>Turn on `use_custom_libcxx` so that gn built libs contain their own libc++ (cargo does not link libc++ in) Partial attempt: https://github.com/denoland/deno/pull/1152</s> not needed
- [x] make cargo package work https://github.com/denoland/deno/issues/1387

**Comment by s-panferov** [comment]
I would really like to be able to use `deno` as a library. My goal is to build an single-executable application server based on rocksdb and deno (or other JS runtime, but deno is a natural choice here). Will it be possible?

**Comment by kitsonk** [comment]
That is one of the goals.

**Comment by ry** [comment]
Cargo build works. Now we just have to figure out how to release.

**Comment by ddibiase** [comment]
Very excited for this release Amazing work team deno!

**Comment by ddibiase** [comment]
Curious when this might be available? Seems like releasing the cargo package is the last step on the list? Any blockers this that community members can help address?

**Comment by ry** [comment]
A crate has been published now https://crates.io/crates/deno

**Comment by qingant** [comment]
Hi, I am new to deno, I write this https://github.com/qingant/tiny-redis to try deno. 
Now I want to make a redis backed by rocksdb, wo I need to access native library by some
way. I search for solution, there seems no native module, ffi in deno currently.

So I found this, but no where to find a doc, can you guys please give me some advise ?

**Comment by bartlomieju** [comment]
@qingant example native plugin: https://github.com/denoland/deno/blob/master/test_plugin/Cargo.toml

**Comment by qingant** [comment]
> @qingant example native plugin: https://github.com/denoland/deno/blob/master/test_plugin/Cargo.toml

got it. Tank you very much.
