### ISSUE TITLE
Deno 2.0 Release Plan

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12110]
## Schedule

- No deadline yet planned.

## Scope

_Note, at this stage it is still subject to change as items get better refined.  This is a working list._

- [ ] Move JavaScript only "stuff" out of the Deno Namespace (#9795)
- [ ] Enable `Deno` namespace by default in workers (#8174)
- [ ] Don't type check be default (#11340)
- [ ] New subprocess API  (#11016, #5501, #11618)
- [ ] JSON Modules (#7623)
- [ ] Turn TypeScript `useUnknownInCatchVariables` on (#11826)
- [ ] Remove deprecated `Deno.customInspect` (#10929)
- [ ] Lockfile generated by default (#11971)
- [ ] op metrics refactoring/cleanup (#12109)
- [ ] Switch JSX/TSX default constructors (#11186)
- [ ] Remove `Deno.read()` and `Deno.write()` (#12107)
- [ ] Have a single configuration for TypeScript (#12111)
- [ ] Internal Origin for Persistance (#11882)
- [ ] Don't report check diagnostics for _external_ scripts by default (#11970)
- [ ] Use `--allow-import` for dynamic imports and workers (#8266)
- [ ] `NotCapable` error to distinguish between permissions and capabilities (#7394)
- [ ] Remove `--ts` flag (it was redundant with `--ext`) (#12198)

**Comment by nayeemrmn** [comment]
Has #10628 been considered?

**Comment by kitsonk** [comment]
@nayeemrmn yes, including just eliminating the subcommand entirely, in the discussions there was no clear path forward, nor did we evaluate it as having a significant upside in terms of usability, so we just put it aside.

**Comment by wojpawlik** [comment]
Please address concerns raised in #8549

**Comment by phil294** [comment]
I was always under the impression that Deno would be backwards-compatible eternally, based on

> As of Deno 1.0.0, the Deno namespace APIs are stable. That means we will strive to make code working under 1.0.0 continue to work in future versions. - [Deno Manual, Stability](https://deno.land/manual@v1.14.1/runtime/stability) / [Release Schedule](https://deno.land/manual@v1.14.1/contributing/release_schedule)

But this is obviously not the case, as there are several breaking changes listed above. Could you release some information on how often major breaking version changes are expected in Deno? This seems like a fairly important question to consider, especially in enterprise context. For example, its strong backwards compatibility is arguably one of the core reasons Java has succeeded in staying relevant over the years. Personally I'm a big fan of Deno but would not really consider it in any large-scale project things keep changing so much.

It's already happening, unfortunately, as a *lot* of Deno code found on the internet does in fact not work anymore (pre 1.0, especially). Often, imports in code samples are dead (removed from std, which itself is also still not stable). A phenomenon quite familiar from web browsing, but in programming languages, a rather unique aspect of Deno.

Anyway, what's the philosophy like for future breaking changes, especially long-term? I was unable to find any information on this

(Not taking into account TS version bumps)

**Comment by vwkd** [comment]
@phil294 I'm always surprised how people want updates on the one hand but then also don't want updates on the other hand. How can you evolve a system without changing it? You're always free to use a specific version of Deno for eternity. Nobody forces you to upgrade. The whole point of semver is to help you see which new version introduces breaking changes. Since this is a major version, I would be surprised if there weren't breaking changes.

**Comment by GJZwiers** [comment]
> 
> 
> How can you evolve a system without changing it?

In Rust this is done through Editions, which allows users to update to the latest versions without breaking code until they specifically opt-in by switching to a newer Edition. For example, in the Rust 2018 Edition the `async` keyword was added which could break existing methods or variables called "async", but it's possible to tell the Rust compiler to not use those breaking changes but still get the bugfixes and non-breaking additions from the latest versions (if I understand correctly).

One of the things @phil294 is concerned about is that Deno 2.0.0 plans to remove methods from the Deno namespace that have already been stabilized. This would more or less break the promise of trying to maintain backwards compatibility with Deno 1.0.0. I think it's a good habit to ~~await~~ keep promises, so it may be worth considering if `Deno.read` and `Deno.write` should really be removed or deprecated instead. These methods may not be used much but runtime stability should apply equally to developers using the most-used Deno APIs and those using less-used, more niche parts. Furthermore, I'm not sure what the reasons for removal are in this case. If they're a blocker for future Deno development or these methods are somehow a real security hazard, then it would make sense to clean them up, of course.

> You're always free to use a specific version of Deno for eternity. Nobody forces you to upgrade.

Well, not always. Let's say a security issue is found in some part of the runtime, which is then patched in version 2.0.1. But maybe you're on version 1.14 and in order to get the patch you need to upgrade to 2 and possibly break things. Not a big deal for a small module, but for a larger codebase it can be trouble especially if it causes a cascade of things breaking due to the fact that something that the project/app heavily depends upon has to be changed (I learned that the hard way :)).

I don't think Deno could create Editions in the same way as Rust, because such a concept would have to be implemented into JavaScript or V8 or something low level like that in order to have modules that are interoperable between different editions. But in any case, it seems important for Deno to have a clear strategy on how backwards compatibility with Deno 1.0 will be maintained.

**Comment by kitsonk** [comment]
Folks, this is not the place to discuss Deno release strategy.  Please use the discussion topics if you wish to that.  This issue is for tracking a planned release.  I have marked comments off topic because of this.

**Comment by ry** [comment]
We've decided to postpone the 2.0 deadline because there are some critical bits we want to figure out still which have uncertain timelines:
- Should CLI have `addEventListener("fetch", _)` support out-of-the-box so it can interoperate with Cloudflare Worker and Deno Deploy scripts?
- Node compatibility (`--compat`)
- How does backwards compatibility and effort towards a Deno configuration file interact?  Does a default `--location` interact well with a `package.json` project directory structure?

I'm going to unpin this issue but leave it open. We do have breaking changes we want to make and will address them - but not yet in November.

**Comment by amithm7** [comment]
@ry 
> Should CLI have addEventListener("fetch", _) support out-of-the-box so it can interoperate with Cloudflare Worker and Deno Deploy scripts?

- I see that [deployctl](https://github.com/denoland/deployctl) was archived. So, is the FetchEvent support coming?

@lucacasonato 's archiving comment:
> You can now run your Deploy scripts with `deno run`: deno.com/deploy/docs/running-scripts-locally

- Doesn't make sense as it requires changes to the script, to create an http server.
- As it says in the deno deploy docs, the API of deno and deno deploy differ: https://deno.com/deploy/docs/runtime-api/
- Deno also hasn't implemented the Service Worker API, which I am guessing what Deno Deploy is based on?  https://github.com/denoland/deno/issues/5957
- So what's the idea here?

**Comment by vwkd** [comment]
> * Should CLI have `addEventListener("fetch", _)` support out-of-the-box so it can interoperate with Cloudflare Worker and Deno Deploy scripts?

@ry I opened https://github.com/denoland/deploy_feedback/issues/107 arguing why designing for compatibility with another service is not a good idea. Irrespective of the why, Cloudflare is also transitioning away from the service worker syntax `addEventListener("fetch", _)` on to a default class export with a `fetch` method. See [Using Durable Objects](https://developers.cloudflare.com/workers/learning/using-durable-objects#instantiating-and-communicating-with-a-durable-object)

**Comment by bartlomieju** [comment]
Deno 2.0 was postponed indefinitely. I'm going to close this issue to avoid confusion about expected feature set and dates. We will open a new issue when the plan clarifies.
