### ISSUE TITLE
compat: tracking issue for running `find-up` test case

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#12999]
This issue is part of #12886

This issue tracks the remaining issue for running the test cases of [find-up](https://npm.im/find-up) in node-compat mode.

- [ ] [ava](https://npm.im/ava) (test runner) doesn't work.
  - [x] It depends on [fs.access](https://nodejs.org/api/fs.html#fsaccesspath-mode-callback) https://github.com/denoland/deno_std/issues/1684
  - [x] It also depends on [inspector](https://nodejs.org/api/inspector.html), which is missing in std/node https://github.com/denoland/deno_std/pull/1688
  - [x] It also depends on [url.parse](https://nodejs.org/api/url.html#urlparseurlstring-parsequerystring-slashesdenotehost), which is missing in std/node https://github.com/denoland/deno_std/issues/1666
  - [x] fs.Stats is missing https://github.com/denoland/deno_std/issues/1689
  - [x] child_process.fork is missing https://github.com/denoland/deno_std/issues/1690

ref #12577

**Comment by bartlomieju** [comment]
Getting `inspector` polyfilled will be a rather involved effort, as we don't have any runtime APIs exposing inspector functionalities. @kt3k could you check which APIs from that module are actually required?

**Comment by kt3k** [comment]
`inspector` is used in ava. ref: https://github.com/avajs/ava/blob/main/lib/cli.js#L119-L121

But if `inspector.url()` returns `undefined`, it seems that ava is not going to use the actual inspector features

**Comment by bartlomieju** [comment]
@kt3k maybe we could shim it for now and always return `undefined`?

**Comment by kt3k** [comment]
`ava@latest` seems needing ipc features (`process.send()`, `process.on("message")`  to communicate with forked child_processes in which the actual test cases are running.. 😬

**Comment by kt3k** [comment]
IPC BoardcastChannel is not available yet https://github.com/denoland/deno/issues/10750

**Comment by kt3k** [comment]
`find-up` now seems working and I can run `nps` command in node compat mode without an issue. (I don't know what exactly fixed the issue, but the issue doesn't reproduce now). Closing

**Comment by bartlomieju** [comment]
> `ava@latest` seems needing ipc features (`process.send()`, `process.on("message")` ) to communicate with forked child_processes in which the actual test cases are running.. 😬

Seems directly related to https://github.com/denoland/deno/issues/12879

**Comment by kt3k** [comment]
Yeah, exactly. Let's track on that issue

I feel IPC features are widely used in npm ecosystem. So I think we need somehow to support it until v0
