### ISSUE TITLE
compat: tracking issue for running npm

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13187]
`npm` (show help message) ✅

- [x] Cannot read properties of undefined at `process.execPath.toUpperCase()` `npm/lib/npm.js:213` https://github.com/denoland/deno_std/pull/1748
- [x] `npm ERR! Exit handler never called!` at the end of the execution https://github.com/denoland/deno_std/issues/1752

`npm init`

- [x] Not Implemented at `vm.runInThisContext` call `promzard/promzard.js:86` in [promzard](https://www.npmjs.com/package/promzard) https://github.com/denoland/deno_std/pull/1747
- [x] Error when ./bin or ./node_modules doesn't exist. Probably something's wrong with readdir error handling https://github.com/denoland/deno_std/issues/1756
- [x] `npm ERR! Exit handler never called!` at the end of the execution https://github.com/denoland/deno_std/issues/1752

`npm install <dep>`

- [x] TypeError: req.abort is not function `minipass-fetch/lib/index.js:73` in [minipass-fetch](https://www.npmjs.com/package/minipass-fetch)
- [x] `npm ERR! request to https://***:undefined@registry.npmjs.org/pretty-bytesnullnullnullnullnullnull failed, reason: this.cb is not a function` looks enigmatic. Something's wrong with https.request?

**Comment by bartlomieju** [comment]
When trying to run `npm init` I get:
```
Not implemented: process.on("uncaughtException")
Not implemented: process.on("unhandledRejection")
npm ERR! Cannot assign to read only property 'name' of function 'class Init extends BaseCommand {
npm ERR!   static description = 'Create a package.json file'
npm ERR!   static params = ['yes', ...<omitted>...
npm ERR! }'
```

**Comment by kt3k** [comment]
@bartlomieju I can't reproduce the above error on my machine. How do you execute npm?

**Comment by kt3k** [comment]
BTW I use `npm@7.21.1`. What version do you use?

**Comment by bartlomieju** [comment]
> @bartlomieju I can't reproduce the above error on my machine. How do you execute npm?

I got it cloned locally, and I execute it like: `deno run --unstable -A --compat --no-check index.js init` (I set up `DENO_NODE_COMPAT_URL` prior to execution). The version is 8.1.4

**Comment by bartlomieju** [comment]
> npm ERR! request to https://***:undefined@registry.npmjs.org/pretty-bytesnullnullnullnullnullnull failed, reason: this.cb is not a function looks enigmatic. Something's wrong with https.request?

This seems like an issue with `ClientRequest` being a class in `std/node`, while in Node it's written in ES5 function class syntax. I'm not 100% sure, but it seems similar to other issues we had when using class based approach.

**Comment by bartlomieju** [comment]
> > npm ERR! request to https://***:[undefined@registry.npmjs.org](mailto:undefined@registry.npmjs.org)/pretty-bytesnullnullnullnullnullnull failed, reason: this.cb is not a function looks enigmatic. Something's wrong with https.request?
> 
> This seems like an issue with `ClientRequest` being a class in `std/node`, while in Node it's written in ES5 function class syntax. I'm not 100% sure, but it seems similar to other issues we had when using class based approach.

`this.cb` being null is actually valid in Node code, however we're handling it not properly. I have no idea why the URL for fetch is mangled so badly, I've been debugging this issue for the past 3 hours and haven't made any progress.

**Comment by bartlomieju** [comment]
`npm install` should now work with latest `deno_std`. Thanks @AaronO for help.

**Comment by kt3k** [comment]
Wow. Great! Thanks! @AaronO

**Comment by kt3k** [comment]
Tried on my machine. I still see this kind of error (with `npm@8.x` & `7.x`):

```
$ npm install pretty-bytes
Not implemented: process.on("uncaughtException")
Not implemented: process.on("unhandledRejection")
error: Uncaught (in promise) TypeError: w.write is not a functiondDeps
    nwritten += await w.write(arr.subarray(nwritten));
                        ^
    at writeAll (file:///Users/kt3k/denoland/deno_std/streams/conversion.ts:350:25)
    at innerWrite (file:///Users/kt3k/denoland/deno_std/node/_fs/_fs_write.js:20:12)
    at Object.write (file:///Users/kt3k/denoland/deno_std/node/_fs/_fs_write.js:23:3)
```

What version have you tested?

**Comment by kt3k** [comment]
nevermind. I found the cause. Will send a PR to std soon

**Comment by kt3k** [comment]
https://github.com/denoland/deno_std/pull/1832

**Comment by bartlomieju** [comment]
Just checked again, and I still can't run latest version of npm (v8):
```
❯ deno run --compat --unstable -A ../cli/bin/npm-cli.js install
Not implemented: process.on("uncaughtException")
Not implemented: process.on("unhandledRejection")
npm ERR! Cannot assign to read only property 'name' of function 'class Install extends ArboristWorkspaceCmd {
npm ERR!   static description = 'Install a package'
npm ERR!   static name = 'instal...<omitted>...
npm ERR! }'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ib/.npm/_logs/2022-02-08T02_04_41_400Z-debug-0.log

```
