### ISSUE TITLE
compat: tracking issue for running yarn's basic sub commands

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13420]
General
- [x] timer.unref() can be fixed by https://github.com/denoland/deno_std/pull/1834
- [x] `os.networkInterfaces()` is not implemented (used for online/offline detection) https://github.com/denoland/deno_std/pull/1846
- [x] Cache folder detection is wrong (`error Yarn hasn't been able to find a cache folder it can use.`)
  - [x] https://github.com/denoland/deno_std/issues/1847 
  - [x] denoland/deno_std#1869

(the above items block executing any of the subcommands)

Sub commands
- [x] yarn install
  - [x] url.resolve is missing https://github.com/denoland/deno_std/pull/1692
  - [x] "punycode.toUnicode is not a function" https://github.com/denoland/deno_std/pull/1857
  - [x] "process.uptime is not a function" https://github.com/denoland/deno_std/pull/1853
  - [x] response.socket is not defined https://github.com/denoland/deno_std/pull/1858
  - [x] response.socket.authorized is not true https://github.com/denoland/deno_std/pull/1858
  - [x] this.cb is not a function in `ClientRequest.prototype._final` https://github.com/denoland/deno_std/pull/1856
  - [x] "fs.createWriteStream is not a function" https://github.com/denoland/deno_std/pull/1859
  - [x] new https.Agent is not implemented https://github.com/denoland/deno_std/issues/1861
  - [x] copyFile with 4 args is not implemented https://github.com/denoland/deno_std/issues/1860
  - [x] https://github.com/denoland/deno_std/issues/1873
  - [x] https://github.com/denoland/deno_std/issues/1875
  - [x] extracted files are corrupted. https://github.com/denoland/deno_std/issues/1887
  - [x] yarn sometimes creates a directory with wrong permission (`0o000` no permission) https://github.com/denoland/deno_std/issues/1893
- [x] yarn add <mod>
- [x] yarn init
- [x] yarn run <command>

----
- [ ] yarn publish <pkg>
- [ ] yarn upgrade
- [ ] yarn upgrade-interactive
