### ISSUE TITLE
`deno_ops` macro tracking issue

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#13943]
https://github.com/denoland/deno/pull/13861 Introduces the `deno_op` proc macro crate. The goal is to produce highly optimized v8 Function callbacks from existing deno ops & provide base for future v8-fast-api work.

Here we tracking down a few things to follow-up after the PR lands:

- [x] Cleanup OpDecl (@AaronO) https://github.com/denoland/deno/pull/13952
- [x] Variable op arity (@AaronO) https://github.com/denoland/deno/pull/13949
- [x] ~~Optimize away unused args (i.e: _foo vs only _)~~ (@AaronO) (not relevant now that all args are optional)
- [x] Allow ops without OpState argument. (@AaronO) https://github.com/denoland/deno/pull/13954
- [x] Infallible / Result-free ops (@AaronO)
- [ ] Less verbose bindings init (@AaronO)
- [ ] Less opcall indirection (@AaronO)
- [ ] Move promise ring to Rust https://github.com/denoland/deno/pull/13906
- [ ] Move unwrapOpResult to Rust (@AaronO)
- [ ] Make [macro generated code](https://github.com/denoland/deno/pull/13861/files#diff-edfa881474570f1c987c98cafcb22b4a45f8861d5f91a642cb7431f51ea42a5cR63-R86) implement a common trait. (@littledivy)
- [ ] Better source file inspection (blocked on rustc) https://github.com/denoland/deno/issues/13939 (@littledivy)
- [ ] Inbuilt permission handling with proc macro attributes. `#[op(unstable)]` (@littledivy)
- [x] Allow sync ops to directly accept `Rc` opstate instead of a mutable borrow across it's lifetime. (@littledivy)

**Comment by bartlomieju** [comment]
@littledivy please update the list

**Comment by littledivy** [comment]
This is mostly done, plus we've got better stuff like fast api and this list is outdated so I'll close this.
