### ISSUE TITLE
Tracking issue for websocket improvements

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#14544]
WebSocket:
- [x] https://github.com/denoland/deno/issues/14280
- [x] https://github.com/denoland/deno/issues/10864
- [x] https://github.com/denoland/deno/issues/11199
- [x] https://github.com/denoland/deno/issues/12815
- [x] https://github.com/denoland/deno/issues/12909

WebSocketStream:
- [x] https://github.com/denoland/deno/issues/13734
- [x] https://github.com/denoland/deno/issues/14050

WebSocket Server:
- [x] https://github.com/denoland/deno/issues/14283
