### ISSUE TITLE
Tracking issue for URL performance

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#15703]
To be on par with WebKit and Blink implementations.

- [ ] https://github.com/denoland/deno/pull/15664
- [x] https://github.com/denoland/deno/pull/15663
- [x] https://github.com/servo/rust-url/pull/761
- [x] https://github.com/servo/rust-url/pull/788
- [x] https://github.com/servo/rust-url/pull/789
- [x] https://github.com/denoland/deno/pull/15800
- [x] https://github.com/denoland/deno/pull/15818
