### ISSUE TITLE
npm specifiers roadmap

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#15960]
- [ ] #16105
- [ ] Post install scripts https://github.com/denoland/deno/issues/16164
- [ ] LSP registry completions #15811
- [ ] automatic acquisition of `@types` package for type checking
- [ ] #16373
- [ ] #16062
- [x] `deno compile` support (https://github.com/denoland/deno/issues/16632)
- [x] `deno vendor` support (https://github.com/denoland/deno/pull/19186)
- [x] optionalDependencies (ex. esbuild)
- [x] repl support https://github.com/denoland/deno/issues/16088
- [x] cache bust npm specifiers more aggressively #16901
- [x] Support non-all lowercase package names (ex. `JSON` vs `json`) (1.28.1)
- [x] `deno install` support (1.28.1)
- [x] peerDependencies (#16561) (1.27.2)
   - for local node_modules: https://pnpm.io/how-peers-are-resolved
- [x] deno info support (1.27.1)
- [x] Lockfile support #15696 (1.27.0)
- [x] Typescript support (1.27.0)
  - LSP
  - Figure out how to have node globals not conflict with deno globals
  - `@deno-types` support
- [x] Node API (n-api) support https://github.com/denoland/deno/pull/13633 (1.27.0)
- [x] Nice error if someone does "npm:react-dom/server@18.2.0" instead of "npm:react-dom@18.2.0/server" (#16131)
- [x] Local node_modules folder #15822 #15971 - pnpm-like node_modules folder
  - [x] Nice to have: https://github.com/denoland/deno/issues/16006
- [x] `--reload=npm:` support #15972
- [x] `deno cache npm:<package>` (#16141)
- [x] https://github.com/denoland/deno/issues/15748
- [x] ~~`deno pack` (prev. bundle) support~~

**Comment by loynoir** [comment]
FYI, you may try `https://esm.sh/{{npm_package}}@{{version}}`, that is self-hostable.

**Comment by kidonng** [comment]
@loynoir off-topic, but I'd like to mention that esm.sh is developed by a Deno team member. Better support for npm specifiers is going to eliminate the need to resort to third-party solutions like such.

**Comment by AnInternetTroll** [comment]
@kidonng I don't want to repeat what was said in #13703, but esm.sh absolutely has it's place in the deno ecosystem. Writing browser compatible code is a goal we should strive for when we can, and esm.sh does it perfectly imo

**Comment by deckchairlabs** [comment]
Just a question regarding `import.meta.resolve`. How will this work if I pass an npm specifier? Will it resolve to the npm registry URL?

**Comment by MarkBennett** [comment]
Is there any plan to support directly running code meant for node?

For example, I'm trying to run `mocha.js` which targets commonjs and uses `require` statements. Is this supported? Is there a way to use an `npm` specifier to import from a local file?

**Comment by tuhanayim** [comment]
Any reason why https://github.com/denoland/deno/blob/main/cli/npm/cache.rs#L222 isn't being tracked here?

**Comment by dsherret** [comment]
@tuhanayim I added it just now. Curious what package you ran into that wasn't all lowercase?

**Comment by tuhanayim** [comment]
@dsherret `@commitlint/cli`. I don't think it's a lower/uppercase mismatch though, it just panics there.

**Comment by tuhanayim** [comment]
Ok, it's because a module named [JSONStream](https://www.npmjs.com/package/JSONStream).

**Comment by Bzvwf16WSDKoSZd8** [comment]
When I using "bitcoinjs-lib" and "bip32" with deno npm specifiers.

(Skipped some code, only showing the related)
```ts
import bitcoin from 'npm:bitcoinjs-lib'
import { BIP32Factory as bip32 } from 'npm:bip32'
import bip39 from 'npm:bip39'
import * as ecc from 'npm:tiny-secp256k1'

let mnemonic = 'mnemonic'
let seed = bip39.mnemonicToSeedSync(mnemonic)
let root = bip32(ecc).fromSeed(seed)
```
This code throw error from "fromSeed()" function which is using hmac SHA512
"error: Uncaught Error: Not implemented: crypto.Hmac"

Because of this, I can't using "bitcoinjs-lib" with deno.
I temporarily using node.js instead until deno implemented "crypto.Hmac".

**Comment by oscarotero** [comment]
Is there any work planned for the task `automatic acquisition of @types package for type checking`? I think this is the cause of TSX warnings about JSX.IntrinsicElements in React, if the jsxImportSource is configured to "npm:react" (it doesn't happen with npm:preact).

**Comment by dsherret** [comment]
@Bzvwf16WSDKoSZd8 there is an open issue here https://github.com/denoland/deno_std/issues/2557

> Is there any plan to support directly running code meant for node?

@MarkBennett not at the moment. That would mean supporting applications written with CommonJS in Deno and having Node globals, which we want to avoid. It would be ideal for Deno to remain ESM only. We probably will support specifiers like `node:fs` in the future though.

> I think this is the cause of TSX warnings about JSX.IntrinsicElements in React, if the jsxImportSource is configured to "npm:react" (it doesn't happen with npm:preact).

@oscarotero would you be able to open an issue for this one? Sounds like there's a pain point here. Thanks.

**Comment by oscarotero** [comment]
@dsherret Done! #16653

**Comment by Bzvwf16WSDKoSZd8** [comment]
> @MarkBennett not at the moment. That would mean supporting applications written with CommonJS in Deno and having Node globals, which we want to avoid. It would be ideal for Deno to remain ESM only. We probably will support specifiers like node:fs in the future though.
I agree. To maintain consistency with the browser code, Deno should only keep the ESM.

**Comment by dsherret** [comment]
@tuhanayim non-all lowercase package name support will be in 1.28.1 (releasing later today) #16669

**Comment by tuhanayim** [comment]
> @tuhanayim non-all lowercase package name support will be in 1.28.1 (releasing later today) #16669

That was quick! Thanks 🙏

**Comment by cmoog** [comment]
Is compatibility with NextJS planned / being tracked?

**Comment by dsherret** [comment]
@cmoog that's something we're looking into, but I recommend opening an issue about anything not working.

**Comment by dsherret** [comment]
If anyone has a question or issue with npm compatibility I recommend opening an issue so that we can track everything individually within issues. That also helps make everything more searchable for others.

**Comment by dsherret** [comment]
Going to close this one as it doesn't seem worth tracking anymore. `deno compile` and `vendor` support will come in 1.34.
