### ISSUE TITLE
Tracking issue for WebSocket performance

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#16315]
Let's look at a simple ping/pong benchmark. 

```js
Deno.serve(req => {
  const { socket, response } = Deno.upgradeWebSocket(req);
  socket.onmessage = (e) => {
    socket.send(e.data);
  }
  return response;
}, { port: 8000 });
```

```
# Deno 1.26.1
Msg/sec: 74114.500000

# uWebSocket.js
Msg/sec: 259207.750000
```

The goal should be to have as little overhead as possible and be on par with uWebSocket.js and tokio-tungstenite. We should also integrate this test using [`uWebSockets/benchmarks/load_test.c`](https://github.com/uNetworking/uWebSockets/blob/45e9ca2372a3758ece3384ac52797da3a3c8fa48/benchmarks/load_test.c) in our CI workflow.

After applying the below changes, I see a **~3.5x improvement** in the above benchmark:
```
# Deno (with below changes)
Msg/sec: 258291.750000
```

- [ ] Optimize `socket[_idleTimeoutDuration]` logic. https://github.com/denoland/deno/pull/16317
- [x] Do not create bunch of Error objects during timer cancellation. https://github.com/denoland/deno/pull/16316
- [x] Make `op_cancel_handle` use fast calls. https://github.com/denoland/deno/pull/16318
- [ ] Use `core.byteLength` instead of doing full utf8 string encoding. https://github.com/denoland/deno/pull/16320
- [ ] Fast path for sending `string` and `binary` values. https://github.com/denoland/deno/pull/16320
- [ ] `op_try_send_[type]` fast call to try to send values in one go without creating a future. https://github.com/denoland/deno/pull/16320
- [ ] Optimize `op_ws_next_event`: 
  - [ ] Make it `deferred`. We don't want to poll unless there is an event. https://github.com/denoland/deno/pull/16325
  - [ ] Since it's deferred, pushing the future onto the event loop should be a fast call. This takes up 10% of the time.
     - [ ] Do not progress deferred ops immediately. https://github.com/denoland/deno/pull/16361
     - [ ] fast calls.
  - [ ] It should return value ID. https://github.com/denoland/deno/pull/16325
  - [ ] Fast path to get values from ID. `NextEventResponse` is slow. https://github.com/denoland/deno/pull/16325
- [ ] `AsyncRefCell` try_borrow_mut before `borrow_mut().await`. https://github.com/denoland/deno/pull/16320
- [x] Optimize Event and MessageEvent:
  - [x] event timestamp does not have to be perfect.
  - [x] `ReflectDefineProperty` causes deopt. https://github.com/denoland/deno/pull/16365
  - [x] Fast path for internal message dispatch to avoid webidl and `ReflectHas` checks. https://github.com/denoland/deno/pull/16365
- [x] Optimize `op_queue_microtask`. https://github.com/denoland/deno/pull/16359
- [x] Do not create a new Uint8Array for `serde_v8::StringOrBuffer`. https://github.com/denoland/deno/pull/16360

A very sloppy implementation of the above can be found here: https://github.com/denoland/deno/compare/main...littledivy:deno:websocket_perf

**Comment by uNetworkingAB** [comment]
Btw, if you like load_test.c there is a similar one for http that performs much better than wrk (and hence gives more accurate numbers) under uSockets/examples/ it's called http_load_test.c.

That benchmark could sure see some improvements, but is pretty fine as is for finding perf. regressions or differences.

**Comment by littledivy** [comment]
Reverted commits (due to bugs):

- [ ] https://github.com/denoland/deno/pull/16501
- [ ] https://github.com/denoland/deno/pull/16743

 cc @billywhizz

**Comment by littledivy** [comment]
Yeah, I'll open a new one soon.
