### ISSUE TITLE
npm compat tracking issue

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#17841]
Tracking issue for npm/node compat issues in `std/node`

Note: Currently we are moving Node polyfill implementation from `std/node` (this repository) to `ext/node` (Deno main repository). ref. https://github.com/denoland/deno/pull/17724

Please wait for a while to contribute to node compat layer

## High priority items
- [ ] socket option in tls.connect https://github.com/denoland/deno/issues/17842 (affects `npm:mssql`)
- [ ] http(s) requests can't upgrade to websocket requests
  - https://github.com/denoland/deno/issues/17846 https://github.com/denoland/deno/issues/17847 (affects `npm:discord.js`)
  - https://github.com/denoland/deno/issues/17496 (affects `npm:puppeteer`, `npm:ws`)
  - https://github.com/denoland/deno/issues/16899 (affects `npm:playwright`)
- [x] http.ClientRequest.setTimeout https://github.com/denoland/deno/issues/17852 https://github.com/denoland/deno/issues/18198 (affects `npm:aws-cdk-lib`)
- [x] crypto.Sign https://github.com/denoland/deno/issues/17843
- [x] crypto.createSecretKey https://github.com/denoland/deno/issues/17844 (affects `npm:next-auth`, `npm:jsonwebtoken`)
- [x] `npm:aws-cdk init` throws TypeError https://github.com/denoland/deno_std/issues/2916 (affects `npm:aws-cdk` (windows)
## Medium priority items
- [x] crypto.generateKeyPairSync https://github.com/denoland/deno/pull/18651 (affects `npm:mineflayer`)
- [ ] missing APIs in `node:os` https://github.com/denoland/deno/issues/17850
- [x] X509Certificate https://github.com/denoland/deno/issues/18455
- [x] node:vm.runInThisContext() https://github.com/denoland/deno/issues/17853
- [x] TypeError: Cannot read properties of undefined (reading 'remoteAddress') #18325
- [x] Use of global process in _events.mjs https://github.com/denoland/deno/issues/17854 (affects `npm:bullmq`
- [x] primisify(execFile) https://github.com/denoland/deno_std/issues/3145 
- [x] crypto.Cipheriv https://github.com/denoland/deno/issues/17848 (affects [tuyapi](https://github.com/codetheweb/tuyapi)) @kt3k
- ...

#### Note about priorities

The priorities are higher when the issue affects popular npm modules (when used via `npm:` specifier).

---

**Comment by jacobmischka** [comment]
Just to tie together a few related other issues, the http task in high priority also affects `npm:ws` (https://github.com/denoland/deno/issues/17496#issuecomment-1453935142) itself, and also `npm:puppeteer` (#17496) and `npm:playwright` (#16899) for some more notable packages.

**Comment by misterjoshua** [comment]
@kt3k Here's another AWS CDK-related npm compatibility issue affecting Deno 1.31.2: #18198

**Comment by bartlomieju** [comment]
Closing in favor of https://github.com/denoland/deno/issues/18836
