### ISSUE TITLE
port remaining std/node unit test cases

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#17840]
We need to port test from https://github.com/denoland/deno_std/tree/0.177.0/node

remaining:
- [x] `node/_fs/_fs_access_test.ts` #18249
- [x] `node/_fs/_fs_appendFile_test.ts` #18262
- [x] `node/_fs/_fs_chmod_test.ts` #18262
- [x] `node/_fs/_fs_chown_test.ts` #18262
- [x] `node/_fs/_fs_close_test.ts` #18262
- [x] `node/_fs/_fs_copy_test.ts` #18262
- [x] `node/_fs/_fs_dir_test.ts` #18463 
- [x] `node/_fs/_fs_dirent_test.ts` #19461
- [x] `node/_fs/_fs_exists_test.ts` #18262
- [x] `node/_fs/_fs_fdatasync_test.ts` #18262
- [x] `node/_fs/_fs_fstat_test.ts` #18262
- [x] `node/_fs/_fs_fsync_test.ts` #18262
- [x] `node/_fs/_fs_ftruncate_test.ts` #18262
- [x] `node/_fs/_fs_futimes_test.ts` #18262
- [x] `node/_fs/_fs_link_test.ts` #18262 
- [x] `node/_fs/_fs_lstat_test.ts` #18262
- [x] `node/_fs/_fs_mkdir_test.ts` #18262
- [x] `node/_fs/_fs_mkdtemp_test.ts` #18262
- [x] `node/_fs/_fs_open_test.ts` #19505
- [x] `node/_fs/_fs_opendir_test.ts` #18262
- [x] `node/_fs/_fs_readFile_test.ts` #18262
- [x] `node/_fs/_fs_read_test.ts` #19588 
- [x] `node/_fs/_fs_readdir_test.ts` #18262
- [x] `node/_fs/_fs_readlink_test.ts` #18262
- [x] `node/_fs/_fs_realpath_test.ts` #18262
- [x] `node/_fs/_fs_rename_test.ts` #18262
- [x] `node/_fs/_fs_rm_test.ts` #18262
- [x] `node/_fs/_fs_rmdir_test.ts` #18262
- [x] `node/_fs/_fs_stat_test.ts` #18262
- [x] `node/_fs/_fs_symlink_test.ts` #18262
- [x] `node/_fs/_fs_truncate_test.ts` #18262
- [x] `node/_fs/_fs_unlink_test.ts` #18262
- [x] `node/_fs/_fs_utimes_test.ts` #18262
- [x] `node/_fs/_fs_watch_test.ts` #18249
- [x] `node/_fs/_fs_writeFile_test.ts` #19524
- [x] `node/_fs/_fs_write_test.ts` #18262
- [ ] `node/_util/_util_callbackify_test.ts` #19664
- [x] `node/assertion_error_test.ts` #19609
- [x] `node/async_hooks_test.ts` #18004 
- [x] `node/buffer_test.ts` #19556
- [ ] `node/child_process_test.ts`
- [x] `node/crypto_test.ts` #19561 
- ~~`node/global_test.ts`~~
- [x] `node/http_test.ts` #18747
- [ ] `node/https_test.ts`
- ~~`node/internal/crypto/_randomBytes_test.ts`~~
- ~~`node/internal/crypto/_randomFill_test.ts`~~
- ~~`node/internal/crypto/_randomInt_test.ts`~~
- ~~`node/internal/crypto/pbkdf2_test.ts`~~
- ~~`node/internal/crypto/scrypt_test.ts`~~
- ~~`node/internal/errors_test.ts`~~ Skip as this is an internal API
- ~~`node/internal/fs/streams_test.ts`~~ Skip as this is an internal API
- ~~`node/internal/util/types_test.ts`~~ tested by compat test case (`parallel/test-util-types.js`)
- ~~`node/internal_binding/_timingSafeEqual_test.ts`~~ Skip as this is an internal API
- ~~`node/internal_binding/node_file_test.ts`~~ Skip as this is an internal API
- ~~`node/module_all_test.ts`~~
- ~~`node/module_test.ts`~~
- [x] `node/net_test.ts` #19663 
- [x] `node/os_test.ts` #19305 
- [x] `node/perf_hooks_test.ts` #19648 
- [ ] `node/process_test.ts`
- [x] `node/querystring_test.ts` #18256
- [x] `node/readline_test.ts` #18256
- [x] `node/string_decoder_test.ts` #18473 
- [x] `node/timers_test.ts` #18472 
- [x] `node/tls_test.ts` #17871
- [x] `node/tty_test.ts` #17868
- ~~`node/upstream_modules_test.ts`~~ We don't have these hard-coded modules anymore
- ~~`node/url_test.ts`~~ no meaningful test cases included
- [x] `node/util_test.ts` #17868
- ~~`node/vm_test.ts`~~ Let's skip this as there's no meaningful test cases
- ~~`node/worker_threads_test.ts`~~ (note: worker_thread is disabled now)

**Comment by maxedahlgren** [comment]
Hi there, I'd like to contribute to this repository and feel like I may be able to help with this issue. It would be great if I could be pointed to where I could find the original test cases

**Comment by fbaltor** [comment]
Is this issue still available? I would like to port the remaining tests.

**Comment by fbaltor** [comment]
Hey, I would like to tackle the `node/_fs/_fs_writeFile_test.ts` port. Just stating here so we avoid duplicate work.

**Comment by fbaltor** [comment]
Working on the `node/_util/_util_callbackify_test.ts`.

**Comment by fbaltor** [comment]
The  `node/buffer_test.ts` is ready in this PR: #19561

**Comment by fbaltor** [comment]
Port of `node/crypto_test.ts` done in: #19561

**Comment by ktfth** [comment]
Read from filesystem PR done to check, please see here: #19588

**Comment by ktfth** [comment]
@kt3k can you help me to understand what is happening on the checks? For #19609

**Comment by fbaltor** [comment]
@ktfth I guess the checks stop at the first failed task. In the case, it is fault is in the `lint debug ubuntu-x86_64` check due to an unformatted file:
![image](https://github.com/denoland/deno/assets/9384697/9810bb29-c4e6-443c-81b1-bfed82ff9463)

**Comment by fbaltor** [comment]
How can we port the `internals` modules? For example `node/internal/fs/streams_test.ts`. In the deno repo the entities being tested (`createReadStream`, `createWriteStream`, `ReadStream` and `WriteStream`) are defined in the file [`ext/node/polyfills/internal/fs/streams.mjs`](https://github.com/denoland/deno/blob/e16b74d792c8fcdb46ab231575fc75f29d4d7fe7/ext/node/polyfills/internal/fs/streams.mjs), but there is no `NodeModulePolyfill` entry for it in the [`ext/node/polyfill.rs`](https://github.com/denoland/deno/blob/b6a3f8f722db89bc136e91da598f581c5838d38e/ext/node/polyfill.rs#L24). Thus I cannot import it in a test file e.g. in `cli/tests/unit_node/internal/streams_test.ts`.

**Comment by bartlomieju** [comment]
@fbaltor I believe you should be able to access them if you use `const require = createRequire(import.meta.url)` (but I'm not 100% sure about that).

**Comment by weartist** [comment]
I want to complete the migration of the following files：

- [ ] node/perf_hooks_test.ts
- [ ]  node/process_test.ts
- [ ]  node/_fs/_fs_read_test.ts
- [ ] node/child_process_test.ts
- [ ]  node/_util/_util_callbackify_test.ts

**Comment by ktfth** [comment]
@weartist the `_fs_read_test.ts` are complete, you can choose another I guess

**Comment by ktfth** [comment]
@kt3k current pr's open by me, are done

**Comment by fbaltor** [comment]
@weartist there is an PR of the `https_test` as well, but it is failing: https://github.com/denoland/deno/pull/19555

**Comment by weartist** [comment]
> @weartist there is an PR of the `https_test` as well, but it is failing, any insights are welcome: #19555还有一个 PR `https_test` ，但它失败了，欢迎任何见解：#19555

haha mine also failed, And I found that the previous http_test also failed

**Comment by ktfth** [comment]
@fbaltor and @weartist maybe the suggestion who wheve made in the PR mentioned previously above could fits well.

**Comment by bartlomieju** [comment]
Gonna close this one as most of the previous cases have been ported and we're actually running a part of Node.js native tests too.
