### ISSUE TITLE
compat: tracking issue for starting a remix project

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#18326]
This issue tracks the problems which blocks starting a new remix project with node.js compat mode of deno.

**Issues with `npx create-remix`** (wizard for creating a new remix project)
- [ ] `TypeError: child_process.execSync is not a function` (used for calling `npm install` in the wizard)

**Issues with `npm install` in remix project**
- [ ] Can't perform `postinstall` script of `core-js-pure` module https://github.com/denoland/deno_std/issues/2013
  - It has `node -e "try{require('./postinstall')}catch(e){}"` in `postinstall`
  - node compat mode doesn't understand `-e` option

**Issues with `npm run dev` in remix project**
- [x] `TypeError: Invalid signal: SIGBREAK` https://github.com/denoland/deno_std/pull/2014
- [x] Error: Not implemented: `ChildProcess.kill()` with the `signal` parameter denoland/deno_std#2083
- [x] `handle.unref()` is not implemented https://github.com/denoland/deno_std/blob/b81ff8e06a134d4ec8940b0fad1440629b0161e7/node/internal_binding/handle_wrap.ts#L46
  - remix uses [get-port](https://www.npmjs.com/package/get-port) module for getting free port, and that module calls [net.createServer().unref()](https://github.com/sindresorhus/get-port/blob/0760c987c17581395d4e30432881dcb0ca6ca94a/index.js#L45)
  - Need unref'd TCP Listener
  - prerequisite work https://github.com/denoland/deno/issues/13886
- [x] `Not implemented: ChildProcess.unref()`
- [x] `child_process.execFileSync is not a function` used in [esbuild](https://github.com/evanw/esbuild/blob/351eb5b49b0a35139387110bb6bf9d10bbcf2292/lib/npm/node.ts#L368)
- [ ] `Cannot read properties of undefined` at `req.connection.remoteAddress` (req.connection is missing) in [forwarded](https://npm.im/forwarded)
- [ ] `TypeError: Cannot read properties of undefined (reading 'encrypted')` at `this.connection.encrypted` in [express](https://npm.im/express)
- [ ] `TypeError: this._implicitHeader is not a function` at `compression/index.js:103` in [express](https://npm.im/express)

**Comment by kwhinnery** [comment]
Just piling on here - I tried using the Remix template for Deno on 1.35 and am seeing a bunch of errors both on start and when trying to preview the project.

https://github.com/remix-run/remix/tree/main/templates/deno

Here's what I see in my console upon attempting to run this project.

```
kevin@kevin-deno my-remix-app % npm run dev

> dev
> npm-run-all build --parallel "dev:*"


> build
> remix build

 info  building... (NODE_ENV=production)
 info  built (121ms)

> dev:remix
> remix watch


> dev:deno
> cross-env NODE_ENV=development deno run --unstable --watch --allow-net --allow-read --allow-env ./build/index.js

Watcher Process started.
Import map diagnostics:
  - Invalid top-level key "comment". Only "imports" and "scopes" can be present.
  - Invalid address "" for the specifier key "// `@remix-run/deno` code is already a Deno module, so just get types for it directly from `node_modules/`".
Watching Remix app in development mode...th/mod.ts (0/2)
💿 Building...://deno.land/std@0.128.0/http/server.ts 20.23KiB/20.23KiB (1/2)
💿 Rebuilt in 141msno.land/std@0.128.0/path/glob.ts (2/10)
Listening on http://localhost:8000
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/_frsh/alive"',
  error: Error: No route matches URL "/_frsh/alive"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/build/entry.client-6TPBIFGI.js"',
  error: Error: No route matches URL "/build/entry.client-6TPBIFGI.js"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/build/_shared/chunk-46RZYS5E.js"',
  error: Error: No route matches URL "/build/_shared/chunk-46RZYS5E.js"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/build/_shared/chunk-DWFMXSZ6.js"',
  error: Error: No route matches URL "/build/_shared/chunk-DWFMXSZ6.js"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/build/root-C4SIFY7A.js"',
  error: Error: No route matches URL "/build/root-C4SIFY7A.js"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/build/routes/_index-CLHRBAGD.js"',
  error: Error: No route matches URL "/build/routes/_index-CLHRBAGD.js"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
ErrorResponse {
  status: 404,
  statusText: "Not Found",
  internal: true,
  data: 'Error: No route matches URL "/build/manifest-7224092C.js"',
  error: Error: No route matches URL "/build/manifest-7224092C.js"
    at getInternalRouterError (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:2043:1090)
    at Object.query (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:1387:19)
    at handleDocumentRequestRR (file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7633:35)
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7576:230
    at file:///Users/kevin/dev/deno-remix/my-remix-app/build/index.js:7732:14
    at eventLoopTick (ext:core/01_core.js:183:11)
}
```

**Comment by bartlomieju** [comment]
@littledivy please take a look at this issue and see if it can be closed

**Comment by littledivy** [comment]
Yes, I think this can be closed.

This works fine:
```
$ deno run -A npm:create-remix@2.6 -y test-app/
$ cd test-app/

$ echo "{ unstable: ['byonm'] }" >> deno.json
$ deno task dev
```

DX not ideal, especially the BYONM part but that's been tracked in #22316
