### ISSUE TITLE
Tracking issue for remaining `node:crypto` APIs

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#18455]
Please leave a comment below if you are planning to contribute so we can avoid duplicate work.

Unimplemented

- [x] `crypto.verify()` @kt3k #18765
- [x]  `crypto.createVerify()` @kt3k #18703
- [x] `crypto.generateKeyPairSync()` @littledivy https://github.com/denoland/deno/pull/18651
- [x] `crypto.generateKeyPair()` @littledivy https://github.com/denoland/deno/pull/18651
- [x] `crypto.X509Certificate` @littledivy https://github.com/denoland/deno/pull/18625
- [x] `crypto.generatePrimeSync()` @littledivy https://github.com/denoland/deno/pull/18861
- [x] `crypto.sign()` @kt3k #18765
- [x]  `crypto.createSign()` @kt3k #18471 
- [x] `crypto.hkdfSync()` @littledivy https://github.com/denoland/deno/pull/18612
- [x] `crypto.hkdf()` @littledivy https://github.com/denoland/deno/pull/18612
- [x] `crypto.getCurves()` @levex https://github.com/denoland/deno/pull/18832
- [ ] #21805
- [x] `crypto.generateKeySync()` @littledivy https://github.com/denoland/deno/pull/18609
- [x] `crypto.generateKey()` @littledivy https://github.com/denoland/deno/pull/18609
- [ ] #21806
- [x] `crypto.getDiffieHellman()` @levex https://github.com/denoland/deno/pull/19137
- [x] `crypto.createECDH()` @levex https://github.com/denoland/deno/pull/18832
- [x] `crypto.createDiffieHellmanGroup()` @levex https://github.com/denoland/deno/pull/19137
- [x] `crypto.createDiffieHellman()` @levex https://github.com/denoland/deno/pull/18943
- [ ] #21807
- [x] `crypto.createPrivateKey()` @littledivy https://github.com/denoland/deno/pull/20981
- [ ] `crypto.Decipheriv.prototype.setAutoPadding`
- [x] `crypto.checkPrimeSync()` @littledivy https://github.com/denoland/deno/pull/18465
- [x] `crypto.generatePrime()` @littledivy https://github.com/denoland/deno/pull/18861
- [x] `crypto.checkPrime()` @littledivy  https://github.com/denoland/deno/pull/18465
- [ ] #21808

Port polyfill to Rust

- [x] `crypto.scryptSync()` @levex #18746
- [x] `crypto.scrypt()` @levex #18746
- [x] `crypto.randomInt()` @levex https://github.com/denoland/deno/pull/18658
- [x] `crypto.randomFill()` @levex https://github.com/denoland/deno/pull/18658
- [x] `crypto.randomFillSync()` @levex https://github.com/denoland/deno/pull/18658
- [x] `crypto.pbkdf2Sync()` @littledivy https://github.com/denoland/deno/pull/18470
- [x] `crypto.pbkdf2()` @littledivy https://github.com/denoland/deno/pull/18470

OpenSSL-specific
- [x] ~~`crypto.setFips()`~~
- [x] ~~`crypto.setEngine()`~~

Identified bugs
- [x] https://github.com/denoland/deno/issues/19002
- [ ] https://github.com/denoland/deno/issues/18972
- [ ] https://github.com/denoland/deno/issues/18928

**Comment by randomicon00** [comment]
I would like to start with the first method `crypto.verify()`

**Comment by Gustrb** [comment]
Can I get assigned to implementing crypto.Decipheriv.prototype.setAutoPadding ?

**Comment by bartlomieju** [comment]
Another one: https://github.com/denoland/deno/issues/19836

**Comment by littledivy** [comment]
Missing AES-GCM in cipher issues:

- https://github.com/denoland/deno/issues/19836
- https://github.com/denoland/deno/issues/20353

**Comment by mllnd** [comment]
Hey @littledivy, has there been any progress with `crypto.Decipheriv.prototype.setAutoPadding`?  Stumbled upon missing method when using `npm:ethereum-cryptography`.

https://github.com/ethereum/js-ethereum-cryptography/blob/cbb283febc4641bf1c5c365a2a16037032f2d23e/src/aes.ts#L69-L71

```
Error: Not implemented: crypto.Cipheriv.prototype.setAutoPadding
    at notImplemented (ext:deno_node/_utils.ts:9:11)
    at Cipheriv.setAutoPadding (ext:deno_node/internal/crypto/cipher.ts:46:9)
```

**Comment by adamtaylor13** [comment]
> `npm:octokit` is not working correctly due to `jsonwebtoken` throwing errors like this:
> 
> ```
> error: Uncaught Error: secretOrPrivateKey must be an asymmetric key when using RS256
>     at Object.module.exports [as sign] (file:///app/node_modules/.deno/jsonwebtoken@9.0.1/node_modules/jsonwebtoken/sign.js:124:22)
> ```

FYI, I wanted to note here for visibility that it seems this issue is fixed in Deno 1.38.1—however, it doesn't appear this is used on Deno Deploy just yet: https://github.com/denoland/deno/issues/20938#issuecomment-1810512827

**Comment by littledivy** [comment]
I have converted the pending items into seperate issues. Closing this one.

**Comment by studiowebux** [comment]
Hello,

I am testing nodejs code that I wrote last year with Deno 2,

I encounter an error when doing the following (I only extracted the errored code)

```typescript
import { generateKeyPairSync } from "node:crypto";

const passphrase: string = "mypassphrase";
const cipher: string = "aes-256-cbc";
const modulusLength: number = 4096;

const key = generateKeyPairSync("rsa", {
  modulusLength,
  publicKeyEncoding: {
    type: "spki",
    format: "pem",
  },
  privateKeyEncoding: {
    type: "pkcs8",
    format: "pem",
    cipher,
    passphrase,
  },
});

console.log(key);
```

Error:
```
error: Uncaught (in promise) Error: PEM error: PEM Base64 error: invalid Base64 length
```

I see above that the `generateKeyPairSync ` has been implemented, do I need to do something special ? 
or `node:crypto` should work as is ?

Thank you !

**Comment by barthuijgen** [comment]
Can't believe you released Deno 2 without fixing setAutoPadding... Luckily Bun does have it implemented.

**Comment by sant123** [comment]
@barthuijgen it is working on canary now
