### ISSUE TITLE
npm compat tracking issue - April 2023

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#18836]
Polyfilling these APIs is our current focus for the next month:

- [x] finish `node:crypto` polyfills - https://github.com/denoland/deno/issues/18455
- [x] https://github.com/denoland/deno/issues/18303 (`npm:mssql`)
- [x] https://github.com/denoland/deno/issues/17847 (`npm:discord.js)
- [x] #17496 (`npm:puppeteer`, `npm:ws`)
- [ ] #16899 (`npm:playwright`)
- [x] #17850 
- [ ] https://github.com/denoland/deno/issues/18730
- [x] https://github.com/denoland/deno/issues/18729
- [x] https://github.com/denoland/deno/issues/16647 (`npm:grpc`)
