### ISSUE TITLE
Deno.serve performance low-hanging fruit

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno#19330]
There's a few places in the new Deno.serve API that could use optimization:

 - [x] The set/get multiple headers methods should use a single, interleaved array rather than an array of tuples. This should reduce garbage dramatically (https://github.com/denoland/deno/blob/main/ext/http/http_next.rs#L248 and https://github.com/denoland/deno/blob/main/ext/http/http_next.rs#L305) (#19336)
 - [x] The set/get headers methods should use raw v8 arrays to avoid serde_v8 entirely
 - [x] `op_http_get_request_method_and_url` should also use a raw v8 array  https://github.com/denoland/deno/blob/main/ext/http/http_next.rs#L208
 - [ ] `op_http_get_request_method_and_url` may be able to use an integer for well-known methods like GET and POST (these are fast-pathed in the http crate https://docs.rs/http/latest/src/http/method.rs.html#73)
 - [ ] There are regular expressions for headers in the flamegraph for Deno.serve. These should be replaced by functions that iterate over chars with a `for` loop, `indexOf`, or some other non-regexp method.
 - [x] `op_http_set_response_header` will likely be faster if we use ByteString or raw v8::String. Needs experimentation (see [write_one_byte](https://docs.rs/rusty_v8/latest/rusty_v8/struct.String.html#method.write_one_byte))
 - [x] We should add a hidden environment variable to more easily test whether http1's writev (https://docs.rs/hyper/1.0.0-rc.3/src/hyper/server/conn/http1.rs.html#286-289) makes things faster or not (https://github.com/denoland/deno/pull/19338)
 - [x] Use `from_maybe_shared_unchecked` for HeaderValue to avoid repeated Latin-1 checks

**Comment by bartlomieju** [comment]
>  There are regular expressions for headers in the flamegraph for Deno.serve. These should be replaced by functions that iterate over chars with a for loop, indexOf, or some other non-regexp method.

We should bench it and see if using function is JS is faster than using a fast op and having these RegExes in Rust

**Comment by bartlomieju** [comment]
Closing for now as this list is outdated.
