### ISSUE TITLE
`node:crypto` private KeyObject tracking issue

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#21124]
- [x] `PrivateKey#asymmetricKeyDetails`
- [x] `PrivateKey#asymmetricKeyType`
- [ ] `PrivateKey#export`
- [x] `createPrivateKey`
  - [x] RSA
    - [x] `pem`
      - [x] `pkcs8` (`PRIVATE KEY`)
      - [ ] `pkcs1` (`RSA PRIVATE KEY`)
    - [x] `der`
      - [x] `pkcs1`
      - [x] `pkcs8`
      - [ ] `sec1`
    - [ ] `jwk`
  - [x] RSA-PSS
    - [x] `pem`
      - [x] `pkcs8` (`PRIVATE KEY`)
      - [ ] `pkcs1` (`RSA PRIVATE KEY`)
    - [x] `der`
      - [x] `pkcs1`
      - [x] `pkcs8`
      - [ ] `sec1`
    - [ ] `jwk`
  - [x] EC
     - [x] `pem`
       - [x] `pkcs8`
       - [ ] `pkcs1`
    - [x] `der`
      - [x] `pkcs1`
      - [x] `pkcs8`
      - [ ] `sec1`
    - [ ] `jwk`
  - [ ] DSA
  - [ ] x25519
  - [ ] x448
  - [ ] ed25519
  - [ ] ed448
  - [ ] dh

Initial PR: https://github.com/denoland/deno/pull/20981

**Comment by muddlebee** [comment]
@littledivy is there anything I can pick up from here? 👀
