### ISSUE TITLE
Coverage reporting feature improvement plans

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#21325]
This suggests improvements in test coverage reporting feature of Deno.

# The problem

Current test coverage reporting feature has several flaws, such as requiring unnecessary boilerplate commands or setups, lacking basic capability, etc.

<details><summary>details</summary>

- It needs 2 commands to produce meaningful output: `deno test --coverage` and `deno coverage`
    - The first command outputs intermediate json files, and the 2nd one produces actual report using them. Separation to 2 commands doesn’t make sense to the users.
- no capability to show reports in html. It requires the external tool (usually [[genhtml](https://github.com/linux-test-project/lcov/blob/master/bin/genhtml)](https://github.com/linux-test-project/lcov/blob/master/bin/genhtml))
- no capability to show them in summary.
- no default paths for intermediate files and lcov report. Always requiring them is unnecessary cognitive overhead and learning barrier
</details>

# Proposed changes

`deno test --coverage` should cover all common tasks about test coverage reporting

- i.e. it should do the same (or similar) as `jest --coverage`
- i.e. `deno test --coverage` should do the following by default:
    - show coverage summaries by files
    - create html coverage report
    - create lcov report
    - have default output path
    - hide internal intermediate json files from the users

# Tasks

- [ ] Add summary reporter to `deno coverage` (non breaking change)
- [ ] Add html reporter to `deno coverage` (non breaking change)
- [ ] Merge `deno coverage` to `deno test --coverage` with 3 default outputs (non breaking change):
    - summary (stdout)
    - lcov (coverage/lcov.info)
    - html (coverage/html)
- [ ] Add default path to `--coverage` option (`./coverage`) (non breaking change)
- [ ] (optional) Move intermediate json files under `$coverage_dir/.raw_data` (non breaking change)
- [ ] (optional) deprecate `deno coverage` command. (breaking change)

**Comment by lucacasonato** [comment]
I like the direction.

What if you run multiple separate `deno test` calls (for example with different flags), and then generate a single coverage report?

**Comment by kt3k** [comment]
> What if you run multiple separate deno test calls (for example with different flags), and then generate a single coverage report?

How about adding some option (like `--merge`), and if that flag is given, the command automatically look up the results (intermediate files) from the previous runs and merge them.

**Comment by lowlighter** [comment]
A merge feature would be nice as it'd allow to combine coverage from different sources too (like when running code in another v8 context, such as browsers when puppeteer)

Also if the summary is being reworked, it may be an opportunity to take a look back at the --threshold in the meantime, I think the previous attempts failed because it was unclear how the total was supposed to be computed

**Comment by jespertheend** [comment]
> hide internal intermediate json files from the users

I'd like to point out that I'm currently relying on the intermediate files so that I can modify coverage data before generating an lcov file.
Specifically, `blob:` urls from the json files are replaced with the paths of files that were used to generate the `blob:` content. [(more info here)](https://github.com/jespertheend/fake-imports?tab=readme-ov-file#coverage)

But the `$coverage_dir/.raw_data` suggestion would totally suit my needs since they would still be accessible. I would only need to update the path of these files.

**Comment by KnorpelSenf** [comment]
I'd love to see #18147 implemented.
