### ISSUE TITLE
tracking: notify of CLI flags and APIs to be removed in Deno v2

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#22021]
Deno v2 is likely the best time to remove deprecated APIs and features. The removal version of these things should be made loud and clear to the user. Features/APIs include:
- [x] `--unstable` flag (https://github.com/denoland/deno/pull/21452)
- [x] `--ts/T` flag in `deno eval` (#22039)
- [x] `--jobs` flag (#22028)
- [x] `--prompt` permission flag (#22038)
- [x] `Deno.cron()` overload (#22035)
- [x] `Deno.customInspect` (#22027)
- [x] `Deno.RequestEvent`, `Deno.HttpConn` and `Deno.serveHttp()` (#22034)
- [x] `Deno.Server` (#22024)
- [x] `deno bundle` (#22062)
- [x] `Deno.ConnectTlsOptions.certFile` (#22026)

Please let us know if anyone knows of or finds any other deprecated APIs or features without a defined removal version.

**Comment by iuioiua** [comment]
What do we want to do with `Deno.flock()`, `Deno.flockSync()`, `Deno.funlock()` and `Deno.funlockSync()`? They've been unstable for years. Should we remove or stabilise them?
