### ISSUE TITLE
Node.js compat roadmap February 2024

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#22337]
API polyfills:

- [x] TLSSocket._start is flaky: https://github.com/denoland/deno/issues/18303

- [ ] `ChildProcess.unref()` kills the process: https://github.com/denoland/deno/issues/21446

- [ ] (SvelteKit) `worker_threads` module doesn't work with `tinypool`: https://github.com/denoland/deno/issues/17248, https://github.com/denoland/deno/issues/20613

- [ ] (Google Cloud) Expose `Http2Session.socket`: https://github.com/denoland/deno/issues/20903

- [x] RSA support in `crypto.sign()`: https://github.com/denoland/deno/issues/18972

- [ ] `crypto.Cipheriv.setAutoPadding()` is not implemented: https://github.com/denoland/deno/issues/21804, https://github.com/denoland/deno/issues/20924

- [x] `crypto.getCipherInfo()` is not implemented: https://github.com/denoland/deno/issues/21805

- [ ] `crypto.diffieHellman()` is not implemented: https://github.com/denoland/deno/issues/21806

- [x] `crypto.createPublicKey()` is not implemented: https://github.com/denoland/deno/issues/21807

- [ ] (VuePress) `process.stdin.unref()` is not implemented: https://github.com/denoland/deno/issues/21796

- [x] `setImmediate().unref()` is not implemented: https://github.com/denoland/deno/issues/21660

- [x] `process.version` seems buggy: https://github.com/denoland/deno/issues/21515

- [x] `process.umask` is not implemented: https://github.com/denoland/deno/issues/20914

- [x] `os.machine()` is not implemented: https://github.com/denoland/deno/issues/20915

- [ ] (mssql) `TlsSocket` resets connection unexpectedly: https://github.com/denoland/deno/issues/20594

- [ ] (Qwik) `ChildProcess.disconnect` event is not implemented: https://github.com/denoland/deno/issues/20612

- [ ] (VitePress) `fs.symlink` doesn't support `junction`: https://github.com/denoland/deno/issues/20609

- [x] `child_process.execSync` is out of sync with `ChildProcess` and doesn't throw an error: https://github.com/denoland/deno/issues/20343

Framework support:

- [ ] Remix crashes on missing export: https://github.com/denoland/deno/issues/20790

- [ ] VuePress seems close to working: https://github.com/denoland/deno/issues/20618

**Comment by bartlomieju** [comment]
I'm going to close this issue since we addressed a good chunk of the problems and we're way past February.
