### ISSUE TITLE
Tracking issue for `tests/` cleanup

### ISSUE THREAD

**Issue by mmastrac** [denoland/deno#22525]
- [ ] Split the `test_util` into the actual test utils and `test_server`, trim the deps on both of them to the minimum necessary
 - [ ] Write docs in the tests/ directory describing each of the types of integration tests and how to run them
 - [ ] Move `tools/node_compat` -> `tests/node_compat/runner`
 - [ ] Move `tools/wpt` -> `tests/wpt/runner`

@iuioiua

**Comment by bartlomieju** [comment]
No longer relevant
