### ISSUE TITLE
tracking: use primordials in Node compatibility layer

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#24236]
Remaining files:

- [ ] `ext/node/polyfills/_utils.ts`
- [ ] `ext/node/polyfills/_brotli.js`
- [ ] `ext/node/polyfills/_http_common.ts`
- [ ] `ext/node/polyfills/_fs/_fs_dir.ts`
- [ ] `ext/node/polyfills/_fs/_fs_cp.js`
- [ ] `ext/node/polyfills/_fs/_fs_lstat.ts`
- [ ] `ext/node/polyfills/_fs/_fs_opendir.ts`
- [ ] `ext/node/polyfills/_fs/_fs_readv.ts`
- [ ] `ext/node/polyfills/_fs/_fs_realpath.ts`
- [ ] `ext/node/polyfills/_fs/_fs_mkdtemp.ts`
- [ ] `ext/node/polyfills/_fs/_fs_readFile.ts`
- [ ] `ext/node/polyfills/_fs/_fs_open.ts`
- [ ] `ext/node/polyfills/_fs/_fs_readdir.ts`
- [ ] `ext/node/polyfills/_fs/_fs_watch.ts`
- [ ] `ext/node/polyfills/_fs/_fs_stat.ts`
- [ ] `ext/node/polyfills/_fs/_fs_common.ts`
- [ ] `ext/node/polyfills/_fs/_fs_fstat.ts`
- [ ] `ext/node/polyfills/_fs/_fs_read.ts`
- [ ] `ext/node/polyfills/_fs/_fs_unlink.ts`
- [ ] `ext/node/polyfills/_fs/_fs_write.mjs`
- [ ] `ext/node/polyfills/_fs/_fs_utimes.ts`
- [ ] `ext/node/polyfills/_fs/_fs_fdatasync.ts`
- [ ] `ext/node/polyfills/_fs/_fs_mkdir.ts`
- [ ] `ext/node/polyfills/_fs/_fs_rmdir.ts`
- [ ] `ext/node/polyfills/_fs/_fs_link.ts`
- [ ] `ext/node/polyfills/_fs/_fs_writev.mjs`
- [ ] `ext/node/polyfills/_fs/_fs_chown.ts`
- [ ] `ext/node/polyfills/_fs/_fs_readlink.ts`
- [ ] `ext/node/polyfills/_fs/_fs_futimes.ts`
- [ ] `ext/node/polyfills/_fs/_fs_rm.ts`
- [ ] `ext/node/polyfills/_fs/_fs_writeFile.ts`
- [ ] `ext/node/polyfills/_fs/_fs_access.ts`
- [ ] `ext/node/polyfills/_fs/_fs_chmod.ts`
- [ ] `ext/node/polyfills/_fs/_fs_close.ts`
- [ ] `ext/node/polyfills/_fs/_fs_ftruncate.ts`
- [ ] `ext/node/polyfills/_fs/_fs_exists.ts`
- [ ] `ext/node/polyfills/_fs/_fs_symlink.ts`
- [ ] `ext/node/polyfills/_fs/_fs_rename.ts`
- [ ] `ext/node/polyfills/_fs/_fs_truncate.ts`
- [ ] `ext/node/polyfills/_fs/_fs_fsync.ts`
- [ ] `ext/node/polyfills/_fs/_fs_copy.ts`
- [ ] `ext/node/polyfills/_process/process.ts`
- [ ] `ext/node/polyfills/_process/streams.mjs`
- [ ] `ext/node/polyfills/string_decoder.ts`
- [ ] `ext/node/polyfills/testing.ts`
- [ ] `ext/node/polyfills/timers.ts`
- [ ] `ext/node/polyfills/_http_outgoing.ts`
- [ ] `ext/node/polyfills/async_hooks.ts`
- [ ] `ext/node/polyfills/process.ts`
- [ ] `ext/node/polyfills/assertion_error.ts`
- [ ] `ext/node/polyfills/path/_posix.ts`
- [ ] `ext/node/polyfills/path/_util.ts`
- [ ] `ext/node/polyfills/path/common.ts`
- [ ] `ext/node/polyfills/path/_win32.ts`
- [ ] `ext/node/polyfills/path/separator.ts`
- [ ] `ext/node/polyfills/http.ts`
- [ ] `ext/node/polyfills/stream/consumers.mjs`
- [ ] `ext/node/polyfills/readline/promises.ts`
- [ ] `ext/node/polyfills/internal/crypto/_randomInt.ts`
- [ ] `ext/node/polyfills/internal/crypto/diffiehellman.ts`
- [ ] `ext/node/polyfills/internal/crypto/hkdf.ts`
- [ ] `ext/node/polyfills/internal/crypto/_keys.ts`
- [ ] `ext/node/polyfills/internal/crypto/cipher.ts`
- [ ] `ext/node/polyfills/internal/crypto/hash.ts`
- [ ] `ext/node/polyfills/internal/crypto/pbkdf2.ts`
- [ ] `ext/node/polyfills/internal/crypto/scrypt.ts`
- [ ] `ext/node/polyfills/internal/crypto/random.ts`
- [ ] `ext/node/polyfills/internal/crypto/_randomFill.mjs`
- [ ] `ext/node/polyfills/internal/crypto/keys.ts`
- [ ] `ext/node/polyfills/internal/crypto/constants.ts`
- [ ] `ext/node/polyfills/internal/crypto/sig.ts`
- [ ] `ext/node/polyfills/internal/crypto/_randomBytes.ts`
- [ ] `ext/node/polyfills/internal/crypto/util.ts`
- [ ] `ext/node/polyfills/internal/crypto/x509.ts`
- [ ] `ext/node/polyfills/internal/validators.mjs`
- [ ] `ext/node/polyfills/internal/querystring.ts`
- [ ] `ext/node/polyfills/internal/util/debuglog.ts`
- [ ] `ext/node/polyfills/internal/util/inspect.mjs`
- [ ] `ext/node/polyfills/internal/errors.ts`
- [ ] `ext/node/polyfills/internal/buffer.mjs`
- [ ] `ext/node/polyfills/internal/async_hooks.ts`
- [ ] `ext/node/polyfills/internal/http.ts`
- [ ] `ext/node/polyfills/internal/readline/promises.mjs`
- [ ] `ext/node/polyfills/internal/readline/utils.mjs`
- [ ] `ext/node/polyfills/internal/readline/emitKeypressEvents.mjs`
- [ ] `ext/node/polyfills/internal/readline/interface.mjs`
- [ ] `ext/node/polyfills/internal/readline/symbols.mjs`
- [ ] `ext/node/polyfills/internal/readline/callbacks.mjs`
- [ ] `ext/node/polyfills/internal/util.mjs`
- [ ] `ext/node/polyfills/internal/stream_base_commons.ts`
- [ ] `ext/node/polyfills/internal/url.ts`
- [ ] `ext/node/polyfills/internal/child_process.ts`
- [ ] `ext/node/polyfills/internal/fixed_queue.ts`
- [ ] `ext/node/polyfills/internal/net.ts`
- [ ] `ext/node/polyfills/internal/hide_stack_frames.ts`
- [ ] `ext/node/polyfills/internal/cli_table.ts`
- [ ] `ext/node/polyfills/internal/primordials.mjs`
- [ ] `ext/node/polyfills/internal/dgram.ts`
- [ ] `ext/node/polyfills/internal/dns/utils.ts`
- [ ] `ext/node/polyfills/internal/dns/promises.ts`
- [ ] `ext/node/polyfills/internal/fs/utils.mjs`
- [ ] `ext/node/polyfills/internal/fs/handle.ts`
- [ ] `ext/node/polyfills/internal/fs/streams.mjs`
- [ ] `ext/node/polyfills/internal/event_target.mjs`
- [ ] `ext/node/polyfills/internal/timers.mjs`
- [ ] `ext/node/polyfills/internal/normalize_encoding.mjs`
- [ ] `ext/node/polyfills/internal/options.ts`
- [ ] `ext/node/polyfills/internal/process/per_thread.mjs`
- [ ] `ext/node/polyfills/internal/console/constructor.mjs`
- [ ] `ext/node/polyfills/internal/idna.ts`
- [ ] `ext/node/polyfills/v8.ts`
- [ ] `ext/node/polyfills/crypto.ts`
- [ ] `ext/node/polyfills/wasi.ts`
- [ ] `ext/node/polyfills/diagnostics_channel.js`
- [ ] `ext/node/polyfills/tls.ts`
- [ ] `ext/node/polyfills/url.ts`
- [ ] `ext/node/polyfills/child_process.ts`
- [ ] `ext/node/polyfills/querystring.js`
- [ ] `ext/node/polyfills/http2.ts`
- [ ] `ext/node/polyfills/inspector.ts`
- [ ] `ext/node/polyfills/os.ts`
- [ ] `ext/node/polyfills/_next_tick.ts`
- [ ] `ext/node/polyfills/net.ts`
- [ ] `ext/node/polyfills/_readline.mjs`
- [ ] `ext/node/polyfills/dgram.ts`
- [ ] `ext/node/polyfills/https.ts`
- [ ] `ext/node/polyfills/_http_agent.mjs`
- [ ] `ext/node/polyfills/dns.ts`
- [ ] `ext/node/polyfills/console.ts`
- [ ] `ext/node/polyfills/_events.mjs`
- [ ] `ext/node/polyfills/perf_hooks.ts`
- [ ] `ext/node/polyfills/internal_binding/udp_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/_utils.ts`
- [ ] `ext/node/polyfills/internal_binding/mod.ts`
- [ ] `ext/node/polyfills/internal_binding/tcp_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/handle_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/uv.ts`
- [ ] `ext/node/polyfills/internal_binding/buffer.ts`
- [ ] `ext/node/polyfills/internal_binding/symbols.ts`
- [ ] `ext/node/polyfills/internal_binding/_timingSafeEqual.ts`
- [ ] `ext/node/polyfills/internal_binding/async_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/pipe_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/util.ts`
- [ ] `ext/node/polyfills/internal_binding/cares_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/stream_wrap.ts`
- [ ] `ext/node/polyfills/internal_binding/_listen.ts`
- [ ] `ext/node/polyfills/internal_binding/node_options.ts`
- [ ] `ext/node/polyfills/internal_binding/node_file.ts`

**Comment by Crystora** [comment]
Hi @bartlomieju @fibibot  I am interested in this issue. Can I pick this up?
