### ISSUE TITLE
tracking: complete runtime documentation

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#24941]
A lot of runtime APIs are missing [documentation](https://docs.deno.com/api). This can mostly be addressed by checking them with [`deno doc --lint`](https://docs.deno.com/runtime/manual/tools/documentation_generator/#linting) on the corresponding TypeScript declaration files:
- [ ] `ext/broadcast_channel/lib.deno_broadcast_channel.d.ts`
- [ ] `cli/tsc/dts/lib.deno_webgpu.d.ts`
- [ ] `cli/tsc/dts/lib.deno.unstable.d.ts`
- [ ] `ext/cache/lib.deno_cache.d.ts`
- [ ] `ext/console/lib.deno_console.d.ts`
- [ ] `ext/url/lib.deno_url.d.ts`
- [ ] `ext/web/lib.deno_web.d.ts`
- [ ] `ext/fetch/lib.deno_fetch.d.ts`
- [ ] `ext/websocket/lib.deno_websocket.d.ts`
- [ ] `ext/webstorage/lib.deno_webstorage.d.ts`
- [ ] `ext/canvas/lib.deno_canvas.d.ts`
- [ ] `ext/crypto/lib.deno_crypto.d.ts`
- [ ] `ext/net/lib.deno_net.d.ts`
- [ ] `cli/tsc/dts/lib.deno.ns.d.ts`
- [ ] `cli/tsc/dts/lib.deno.shared_globals.d.ts`
- [ ] `cli/tsc/dts/lib.deno.window.d.ts`

A follow-up tracking issue could be created once this work is done to make documentation more extensive using the [JSDoc checker](https://github.com/denoland/deno/blob/main/tools/jsdoc_checker.js). E.g. assert that all class methods have at least one `@example` JSDoc tag. A similar approach was used to make the Standard Library's documentation great.

**Comment by littledivy** [comment]
Done in https://github.com/denoland/deno/pull/34715
