### ISSUE TITLE
`FileHandle` missing methods

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#25554]
FileHandle class (in `node:fs/promises`) still misses the below methods:

ref: https://nodejs.org/api/fs.html#class-filehandle

- [ ] Event: 'close'
- [ ] filehandle.appendFile(data[, options])
- [x] filehandle.chmod(mode) #27522 
- [x] filehandle.chown(uid, gid) #27638
- [x] filehandle.close() https://github.com/denoland/deno/pull/19357
- [x] filehandle.createReadStream([options]) #27591 #28700
- [x] filehandle.createWriteStream([options]) #28700
- [x] filehandle.datasync() #27677
- [x] filehandle.fd
- [x] filehandle.read(buffer, offset, length, position) #19359
- [x] filehandle.read([options]) #19359
- [x] filehandle.read(buffer[, options]) #19359
- [ ] filehandle.readableWebStream(options) #31745
- [x] filehandle.readFile(options)
- [ ] filehandle.readLines([options])
- [ ] filehandle.readv(buffers[, position])
- [x] filehandle.stat([options]) #26719
- [x] filehandle.sync() #27677
- [x] filehandle.truncate(len) #27389
- [x] filehandle.utimes(atime, mtime) #27582
- [x] filehandle.write(buffer, offset[, length[, position]]) #19385
- [x] filehandle.write(string[, position[, encoding]]) #19385
- [x] filehandle.writeFile(data, options) #25555
- [x] filehandle.writev(buffers[, position]) #27563

_Originally posted by @k-nasa in https://github.com/denoland/deno/issues/19165#issuecomment-1574509694_

**Comment by obafemitayor** [comment]
@kt3k Can I work on this?

**Comment by kt3k** [comment]
Yes please

**Comment by kt3k** [comment]
Note to contributors: Please read the Node.js source code of FileHandle class first (you can find it here https://github.com/nodejs/node/blob/main/lib/internal/fs/promises.js) and make the implementation as close as possible to it.

**Comment by SebastienGllmt** [comment]
It seems that, since this issue was last updated,

Newly completed
- [x] filehandle.chown(uid, gid) #27638
- [x] filehandle.datasync() #27677
- [x] filehandle.sync() #27677

In-progress
- [ ] filehandle.createReadStream([options]) #28700 
- [ ] filehandle.createWriteStream([options]) #28700

**Comment by SebastienGllmt** [comment]
This was accidentally closed early by #31745 because the PR used the word "Closes" (and Github automatically closes issues when you use `Closes <Issue Number>`)

**Comment by AprilNEA** [comment]
I was going through this issue and noticed that all the remaining unchecked items have actually been implemented already:                                                                        

  - Event: 'close' — has been working for a while (this.emit("close") in the close() method)
  - filehandle.appendFile() — landed in #31301
  - filehandle.readLines() — landed in #31107
  - filehandle.readv() — landed in #31943

  Together with readableWebStream() from #31745, that covers the full checklist.
