### ISSUE TITLE
`--unstable-detect-cjs` tracking issue

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#26225]
- [x] Initial PR https://github.com/denoland/deno/pull/26149
- [ ] Cache busting and support in the LSP (ex. have a file that's CJS and then modify it to be ESM, it should update CjsTracker accordingly)
- [x] Improve error messages to recommend using this flag (https://github.com/denoland/deno/pull/26287).

**Comment by bartlomieju** [comment]
Update `docs.deno.com` to mention `type: "commonjs"` and `--unstable-detect-cjs` in https://docs.deno.com/runtime/fundamentals/node/#commonjs-support
