### ISSUE TITLE
API changes to Ops

### ISSUE THREAD

**Issue by ry** [denoland/deno#2730]
<a href="https://github.com/denoland/deno/blob/ddee2dff14772ade16e282ad18eda6f5054ce94e/cli/ops.rs">ops.rs</a> has grown to over 2000 lines and needs to be broken up.

We additionally have seen performance problems for very hot ops like read/write with flatbuffers. This has necessitated the ability to handle non-flatbuffer message (see [dispatch_minimal.ts](https://github.com/denoland/deno/blob/ddee2dff14772ade16e282ad18eda6f5054ce94e/js/dispatch_minimal.ts)). We want to allow ops to use their own serialization - flatbuffers, JSON, serde, or just a custom message format.

We want the ability to dynamically load (dlopen) ops that are not included in the deno executable. See preliminary work in https://github.com/denoland/deno/pull/2385.

Thus I want to do the following changes:

- [x] #2753 Breaking up cli/ops.rs into cli/ops/read_write.rs, cli/ops/subprocess.rs, cli/ops/fetch.rs, ...

- [ ] Create a new OpDispatcher trait which has a name in addition to a dispatch function. This allows us to create subtraits like `FlatBufferOpDispatcher` which would allow simplify a lot of the parsing/serialization code. [Example code](https://gist.github.com/piscisaureus/5f1fc257e57cb976ec446eed03fb76f5).

- [x] Add a new method to register op dispatchers dynamically. This would be called even for built-in ops at startup. `isolate.register_op(op_read)` #3039 (and others)
- [x] #2734 Add a new integer parameter to `Deno.core.dispatch()` to specify which op is being called.
```typescript
let readId: number = null;
function read(fd: number, buf: Uint8Array): number {
  if (!readId) {
    readId = Deno.core.ops["read"]; // lazy lookup
  }
  /* ... */ 
  Deno.core.dispatch(readId, cntrolbuf, zerobuf);
  /* ... */
}
``` 
Note the new `Deno.core.ops` which allows us to retrieve an op id from a string. (We're worried that passing the string directly to `Deno.core.dispatch` would be slow)

**Comment by bartlomieju** [comment]
> 1. Breaking up cli/ops.rs into cli/ops/read_write.rs, cli/ops/subprocess.rs, cli/ops/fetch.rs, ...

I'll be working on this

**Comment by ry** [comment]
I consider this closed in #3039. I'm sure there are other op changes, but at least we can dynamically import ops now using Isolate::register_op
