### ISSUE TITLE
Use Github Actions for CI/CD

### ISSUE THREAD

**Issue by ry** [denoland/deno#2979]
We've landed github actions in https://github.com/denoland/deno/pull/2966 but we have not yet removed the existing Travis/Appveyor CI. There is still work to do:

- [x] gh-pages deployment for benchmarks #3049
- [ ] releases on tagged commits #3052
- [x] Add GHA badges in README.md and on website/index.html #3056 
- [ ] Remove .travis.yml and .appveyor.yml
