### ISSUE TITLE
cli/js test runner TODO

### ISSUE THREAD

**Issue by ry** [denoland/deno#4345]
- [ ] filtering tests from the command line. I should be able to run a single unit tests by doing something like `./target/debug/deno -A cli/js/tests/unit_test_runner.ts bufferBasicOperations`.
- [ ] The output `OK     bufferReadEmptyAtEOF (2ms)` is not ideal. It should rather match how Rust does it `testing bufferReadEmptyAtEOF .... ok`. In particular it should output `testing bufferReadEmptyAtEOF .... ` before the test completes.
- [ ] When there is a test failure in `cli/js/tests`, the unit test runner does not print which test failed at the bottom of the output. The user has to scroll up through the tests to find the failed test.
- [ ] When running "cargo test" and the js_unit_tests fails, it causes a cascade of other test failures. This is related to how the tools/http_server.py is shut down. 
```
Unit tests failed
test js_unit_tests ... FAILED
test lock_check_err ... FAILED
test lock_check_ok ... FAILED
test test_pattern_match ... ok
test test_permissions_net_connect_allow_deno_land ... FAILED
test test_permissions_net_connect_allow_localhost_ip ... FAILED
test test_permissions_net_connect_allow_localhost_ip_4545_fail ... FAILED
test test_permissions_net_connect_allow_localhost_ip_4555 ... FAILED
test test_permissions_net_fetch_allow_deno_land ... FAILED
test test_permissions_net_fetch_localhost ... FAILED
test test_permissions_net_fetch_allow_localhost_4545 ... FAILED
test test_permissions_net_fetch_localhost_4545_fail ... FAILED
test target_test ... ok
```

 People who are adding features need a quick guide and shouldn't have to read through the increasingly complex test runner code. Add information to `cli/js/tests/README.md`:
  - [ ]  how to run specific tests
  - [ ] how to get raw stdout/stderr of tests. 
  - [ ] how to run tests with specific permissions, avoiding the test runner parent process.

**Comment by bartlomieju** [comment]
@ry just a few comments so we're on the same page.

> * [ ]  The output `OK     bufferReadEmptyAtEOF (2ms)` is not ideal. It should rather match how Rust does it `testing bufferReadEmptyAtEOF .... ok`. In particular it should output `testing bufferReadEmptyAtEOF .... ` before the test completes.

To implement that I'd need to emit 2 `Deno.TestEvent`s - one when test begins running and one after test finishes - `testStart` and `testEnd`.
Then `ConsoleReporter` outputs `testing bufferReadEmptyAtEOF .... ` on `testStart` and then on `testEnd` clears empty line and writes `OK/FAILED`

> * [ ]  When there is a test failure in `cli/js/tests`, the unit test runner does not print which test failed at the bottom of the output. The user has to scroll up through the tests to find the failed test.

To match Rust's behavior exactly we'd just print `FAILED` after test name and print errors only at the end; does that sound ok?

> * [ ]  When running "cargo test" and the js_unit_tests fails, it causes a cascade of other test failures. This is related to how the tools/http_server.py is shut down.

That's trivial to fix for `js_unit_tests`

> People who are adding features need a quick guide and shouldn't have to read through the increasingly complex test runner code. Add information to `cli/js/tests/README.md`:
> 
> * [ ]   how to run specific tests
> * [ ]  how to get raw stdout/stderr of tests.
> * [ ]  how to run tests with specific permissions, avoiding the test runner parent process.

No problem, but that means a few more CLI flags in `unit_test_runner.ts` - I'll pull `std/flags` for that.
