### ISSUE TITLE
[tracker] std/node/errors

### ISSUE THREAD

**Issue by disizali** [denoland/deno#5944]
_if we want to be compatible with node's API, we must be kind to its errors too._

we should support node's API errors listed [here](https://nodejs.org/dist/latest-v14.x/docs/api/errors.html) to be more consistent about errors.

todo list : 
- [ ] create error module in std/node
- [ ] support node error codes ( like [ERR_INVALID_CALLBACK](https://nodejs.org/dist/latest-v12.x/docs/api/errors.html#errors_err_invalid_callback) )
- [ ] replace handwritten errors with error codes ( like [HERE](https://github.com/denoland/deno/blob/49c70774012e929b3c77b808edc5a7908bcb6fa2/std/node/_fs/_fs_appendFile.ts#L27) )
