### ISSUE TITLE
1.4.0 manual checklist

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7422]
- [x] update https://deno.land/manual/getting_started/typescript describing `isolatedModules` and `importsNotUsedAsValues`
- [x] update list of rules in https://deno.land/manual/tools/linter (waiting on final deno_lint update)
- [x] update output in https://deno.land/manual/tools/dependency_inspector
- [x] update https://deno.land/manual/tools/documentation_generator about `export { foo, bar }`
- [x] update "Limitations" in https://doc.deno.land/about
- [x] add info about "File watcher" to manual (https://github.com/denoland/deno/pull/7382)
- [x] add info about coverage in https://deno.land/manual/testing

CC @lucacasonato

**Comment by bartlomieju** [comment]
Related: it seems that `Deno.systemMemoryInfo()` hasn't been added to list of unstable features.

**Comment by lucacasonato** [comment]
We should also hide `--no-check` for `deno info` now, as it is not used anymore.
