### ISSUE TITLE
Q1 2021 roadmap

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8824]
Roadmap Q1 2021

Scheduled releases:
- 1.7.0 - January, 19th
- 1.8.0 - March, 2nd

_planned features and refactors_:

- [ ] consuming external source maps (#4499, #8054) _this is partially done, by consuming inlined source maps_
- [ ] support for React 17 jsx (`swc`) (#8440)
- [x] structured clone API for workers (#3557) _in `deno.core` (#9458) but needs to be integrated into workers_
- [ ] Import Assertions/JSON Modules (#7623)
- [ ] lint: Ignore directives should affect the entire next AST node https://github.com/denoland/deno_lint/issues/476
- [x] Review alignment to spec and stabilise import maps (#9461, #4958)
- [x] WebGPU support (#7863, #7977)
- [x] Stabilize runtime permissions APIs (#9573)
- [x] `data:` URL support (#5059)
- [x] refactor runtime compiler APIs (#4752)
- [x] support access tokens for remote modules (#5239)
- [x] IIFE bundles (#9204, #9291)
- [x] lite binaries for `deno compile` (#8757, #9141)
- [x] ICU (`rusty_v8`) (#1968, https://github.com/denoland/rusty_v8/pull/390)
- [x] Test built in Web APIs with WPT (#9001)
- [X] Re-align whatwg streams to current standards

_maybe_:

- [x] HTTP/2 and QUIC support (https://github.com/denoland/deno/pull/9935)
- [ ] Web Crypto APIs support (#1891)
- [x] deno test --docs (#4716, #7916)
- [ ] type definitions for bundles (#3385)
- [ ] V8 Fast API for ops (`rusty_v8`, `deno_core`)
- [x] `blob:` URL support (#9210, #10045)

**Comment by yos1p** [comment]
+1 on HTTP2 support

**Comment by newtack** [comment]
Ensuring deno lsp and VSCode work seamlessly?

**Comment by rkawajan** [comment]
+1 on HTTP2 support

**Comment by kitsonk** [comment]
> Ensuring deno lsp and VSCode work seamlessly?

There will be continued work on the lsp, we just didn't know exactly what features.

**Comment by jveres** [comment]
Suggestion: add real world example testing.
I know deno is not yet mature but having those numerous swc issues in each new release makes no confidence in using it in prod.

**Comment by Soremwar** [comment]
@jveres SWC bugs are tracked in the SWC repo, where "real world code" is seemingly now a part of the tests for the latest refactor https://github.com/swc-project/swc/pull/1264

**Comment by leoc11** [comment]
+1 V8 Fast API for ops

**Comment by kitsonk** [comment]
I have seen a bit of mis-understanding going on in issues... To be clear, these issue are to broadcast what the core team's priorities are for the quarter, and all of these will be worked on by the core team.  If you want to help out, feel free to provide input.

If you want to contribute to Deno though, it is best to look at resolving issues that are not on this list.  If it is any sort of significant feature, it is best to get consensus and alignment from the core team before you start on the feature, as without that feedback it will likely only lead to significant delays or even abandonment of your work.  The best way to get that feedback is on the issue itself.

At the moment, the core team consists of:

- @ry
- @bartlomieju 
- @lucacasonato 
- @piscisaureus 
- @bnoordhuis 
- @kitsonk 

There are several other long term contributors who can give you advice and suggestions as well.

**Comment by devalexqt** [comment]
More security options.

**Comment by fanweixiao** [comment]
waiting on QUIC support

**Comment by StEvUgnIn** [comment]
Server-side rendering (SSR) native support

**Comment by kitsonk** [comment]
This isn't the place to put random comments about a wish list. This is an issue to communicate what the core team is working on. Other suggestions should be made in their own issue or discussions, and with more detail than a couple words.

**Comment by bartlomieju** [comment]
Q1 is long gone and relevant issues have been rolled to Q3 roadmap.
